export const Actions = {
	SET_AUTOMATION: 'SET_AUTOMATION',
	SET_CONNECTION_DETAILS: 'SET_CONNECTION_DETAILS',
	UPDATE_STATE_VALUES: 'UPDATE_STATE_VALUES',
	UPDATE_AUTOMATION: 'UPDATE_AUTOMATION',
	SET_EXECUTION_HISTORY: 'SET_EXECUTION_HISTORY',
	SET_PREVIOUS_STEP_RESPONSE: 'SET_PREVIOUS_STEP_RESPONSE',
	EXECUTE_AUTOMATION: 'EXECUTE_AUTOMATION',
	SET_PREVIOUS_EXECUTION_DATA: 'SET_PREVIOUS_EXECUTION_DATA',
	SET_VARIABLES: 'SET_VARIABLES',
};
