export const Actions = {
	SET_AUTOMATION: 'SET_AUTOMATION',
	SET_CONNECTION_DETAILS: 'SET_CONNECTION_DETAILS',
	UPDATE_STATE_VALUES: 'UPDATE_STATE_VALUES',
	UPDATE_AUTOMATION: 'UPDATE_AUTOMATION',
};
