export const Actions = {
	SET_AUTOMATION: 'SET_AUTOMATION',
	SET_AUTOMATIONS_LIST: 'SET_AUTOMATIONS_LIST',
	SET_CONNECTION_DETAILS: 'SET_CONNECTION_DETAILS',
	UPDATE_STATE_VALUES: 'UPDATE_STATE_VALUES',
	UPDATE_AUTOMATION: 'UPDATE_AUTOMATION',
	SET_EXECUTION_HISTORY: 'SET_EXECUTION_HISTORY',
	SET_VARIABLES: 'SET_VARIABLES',
	UPDATE_CONTEXT_STATE_IN_AUTOMATION_BUILDER: 'UPDATE_CONTEXT_STATE_IN_AUTOMATION_BUILDER',
	RESET_VARIABLES: 'RESET_VARIABLES',
};
