export const Actions = {
	SET_KNOWLEDGE_BASE_FILES: 'SET_KNOWLEDGE_BASE_FILES',
	SET_EXISTING_AI_ASSISTANTS: 'SET_EXISTING_AI_ASSISTANTS',
	SET_ACTIVE_AI_ASSISTANT_DETAILS: 'SET_ACTIVE_AI_ASSISTANT_DETAILS',
	RESET_STATE: 'RESET_STATE',
};
