export const Actions = {
	SET_KNOWLEDGE_BASE_FILES: 'SET_KNOWLEDGE_BASE_FILES',
	SET_EXISTING_AI_ASSISTANTS: 'SET_EXISTING_AI_ASSISTANTS',
	SET_ACTIVE_AI_ASSISTANT_DETAILS: 'SET_ACTIVE_AI_ASSISTANT_DETAILS',
	SET_ASSIGNED_WORKFLOWS_TO_AI_ASSISTANT: 'SET_ASSIGNED_WORKFLOWS_TO_AI_ASSISTANT',
	SET_WORKFLOWS: 'SET_WORKFLOWS',
	SET_AI_CHAT_SESSIONS: 'SET_AI_CHAT_SESSIONS',
	RESET_STATE: 'RESET_STATE',
};
