export const Actions = {
	SET_LIST_ITEMS: 'SET_LIST_ITEMS',
	SET_SUB_TASKS: 'SET_SUB_TASKS',
	ADD_SUB_TASK: 'ADD_SUB_TASK',
	REMOVE_SUB_TASK: 'REMOVE_SUB_TASK',
	UPDATE_SUB_TASK: 'UPDATE_SUB_TASK',
	RESET_SUB_TASKS: 'RESET_SUB_TASKS',
	RESET_STATE: 'RESET_STATE',
};
