image: atlassian/default-image:3

clone:
    depth: full

definitions:
    steps:
        - step: &build-and-test
              name: Build and Test
              script:
                  - echo 'Running tests...'
                  - echo 'Building...'
        - step: &sync-to-github
              name: Sync to GitHub
              script:
                  - echo 'Starting GitHub sync...'
                  - git config --global user.name 'Bitbucket-GitHub Sync'
                  - git config --global user.email 'noreply@bitbucket.org'
                  - git remote add github https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/${GITHUB_USERNAME}/${BITBUCKET_REPO_SLUG}.git
                  - git push github --all --force
                  - git push github --tags --force

pipelines:
    branches:
        master:
            - step: *build-and-test
            - step: *sync-to-github
        development:
            - step: *build-and-test
            - step: *sync-to-github
        feature/change-iframe:
            - step: *build-and-test
            - step: *sync-to-github
