module.exports = {
	// api_server: 'https://api.huemn.com/galleries/dev',
	// proposal_api_server: 'https://api.huemn.com/proposals/dev',
	tenant_user_api_server: 'https://api.ve.co/tenant-users/1.0',
	tenant_api_server: 'https://api.ve.co/tenants/1.0',
	// notification_api_server: 'https://api.huemn.com/notifications/1.0',
	// image_api_server: 'https://api.huemn.com/images/1.0/',
	// form_api_server: 'https://api.huemn.com/forms/2.0',
	// projects_api_server: 'https://api.huemn.com/projects/dev',
	// forms_graphql_server: `https://api.huemn.com/forms/dev`,
	tenant_users_api: 'https://api.ve.co/tenant-users/1.0',
	// tenant_users_api: 'http://192.168.2.192:6000',
	ve_conversations_api: 'https://api.ve.co/ve-conversations/1.0',
	proposals_api: 'https://api.ve.co/proposals/1.0',
};
