export const Actions = {
	GET_TENANTS_LIST: 'GET_TENANTS_LIST',
	GET_TENANTS_PREFERENCES: 'GET_TENANTS_PREFERENCES',
	GET_CLIENT_PORTAL_PREFERENCES: 'GET_CLIENT_PORTAL_PREFERENCES',
	GET_TENANTS_SUBSCRIPTION_DETAILS: 'GET_TENANTS_SUBSCRIPTION_DETAILS',
	GET_AI_CREDITS_USED: 'GET_AI_CREDITS_USED',
	RESET_STATE: 'RESET_STATE',
};
