export const Actions = {
	GET_TENANTS_LIST: 'GET_TENANTS_LIST',
	GET_TENANTS_PREFERENCES: 'GET_TENANTS_PREFERENCES',
	GET_TENANTS_SUBSCRIPTION_DETAILS: 'GET_TENANTS_SUBSCRIPTION_DETAILS',
	RESET_STATE: 'RESET_STATE',
};
