export const Actions = {
	GET_TENANTS_LIST: 'GET_TENANTS_LIST',
	GET_TENANTS_PREFERENCES: 'GET_TENANTS_PREFERENCES',
	GET_CLIENT_PORTAL_PREFERENCES: 'GET_CLIENT_PORTAL_PREFERENCES',
	GET_TENANTS_SUBSCRIPTION_DETAILS: 'GET_TENANTS_SUBSCRIPTION_DETAILS',
	GET_TASK_PREFERENCES: 'GET_TASK_PREFERENCES',
	RESET_STATE: 'RESET_STATE',
};
