export const Actions = {
	GET_WORKFLOW_DETAILS_SUCCESS: 'GET_WORKFLOW_DETAILS_SUCCESS',
	GET_ALL_TEMPLATES_INFO_SUCCESS: 'GET_ALL_TEMPLATES_INFO_SUCCESS',
	GET_ALL_CLIENT_LIST_SUCCESS: 'GET_ALL_CLIENT_LIST_SUCCESS',
	UPDATE_STATE_VALUES_SUCCESS: 'UPDATE_STATE_VALUES_SUCCESS',
	GET_SPECIFIC_TEMPLATE_INFO_SUCCESS: 'GET_SPECIFIC_TEMPLATE_INFO_SUCCESS',
	GET_ALL_EMAIL_TEMPLATES_SUCCESS: 'GET_ALL_EMAIL_TEMPLATES_SUCCESS',
	RESET_STATE: 'RESET_STATE',
};
