export const Actions = {
	GET_NOTES_SUCCESS: 'GET_NOTES_SUCCESS',
	GET_MORE_NOTES_SUCCESS: 'GET_MORE_NOTES_SUCCESS',
	CREATE_NOTES_PAGE: 'CREATE_NOTES_PAGE',
	GET_NOTES_PAGE_DATA_SUCCESS: 'GET_NOTES_PAGE_DATA_SUCCESS',
	RESET_STATE: 'RESET_STATE',
};
