export const Actions = {
	SET_CLIENT_LIST: 'SET_CLIENT_LIST',
	UPDATE_CONTACT_CONTEXT: 'UPDATE_CONTACT_CONTEXT',
	RESET_STATE: 'RESET_STATE',
	SET_CONTACT_METADATA: 'SET_CONTACT_METADATA',
	UPDATE_CONTACT_VIEWS: 'UPDATE_CONTACT_VIEWS',
	DELETE_CONTACT_VIEW: 'DELETE_CONTACT_VIEW',
	SET_CONTACT_PREFERENCES: 'SET_CONTACT_PREFERENCES',
};
