export const Actions = {
	GET_USERS_FROM_META_SUCCESS: 'GET_USERS_FROM_META_SUCCESS',
	GET_USERS_FROM_META_FAILURE: 'GET_USERS_FROM_META_FAILURE',
	GET_USERS_ALL_CONVERSATIONS_SUCCESS: 'GET_USERS_ALL_CONVERSATIONS_SUCCESS',
	GET_USERS_ALL_CONVERSATIONS_FAILURE: 'GET_USERS_ALL_CONVERSATIONS_FAILURE',
	GET_PAGEINFO_DATA_SUCCESS: 'GET_PAGEINFO_DATA_SUCCESS',
	GET_PAGEINFO_DATA_FAILURE: 'GET_PAGEINFO_DATA_FAILURE',
	GET_PAGEINFO_CHAT_FILTERS_COUNT_SUCCESS: 'GET_PAGEINFO_CHAT_FILTERS_COUNT_SUCCESS',
	GET_PAGEINFO_CHAT_FILTERS_COUNT_FAILURE: 'GET_PAGEINFO_CHAT_FILTERS_COUNT_FAILURE',
};
