export const pricingPlansData = {
	plans: {
		free: {
			name: 'Free',
			features: [
				'5 meetings/month',
				'30 mins/meeting',
				// 'Live summaries',
				// 'Speaker ID',
				// '5 Pro Queries/meeting',
				// '1 personal agent',
				// `100 runs/month`,
				// 'No multi-agent support',
				// `10 files (100MB total, 5MB/file)`,
				`100 credits/day`,
				`Basic auth`,
				`Help Center`,
			],
			isSeatBased: false,
		},
		// plus: {
		// 	name: 'Plus',
		// 	features: [
		// 		'Advanced user engagement analytics',
		// 		'Integrate with 50+ apps',
		// 		'Collaborate with 15 members',
		// 		'AI-powered content generation',
		// 		'Dedicated priority support',
		// 		'Custom workspace branding',
		// 		// '250GB secure cloud storage',
		// 	],
		// 	trialDays: 2,
		// 	isSeatBased: false,
		// },
		Plus: {
			name: 'Plus',
			features: [
				'Unlimited meetings/month',
				'Unlimited mins/meeting',
				'Multi-agent support',
				'1,990 credits/month',
				// 'Help Centre',
				'Email support (12–24 hr response)',
			],
			isSeatBased: true,
		},
		Pro: {
			name: 'Pro',
			features: [
				`Unlimited meetings`,
				`Unlimited Pro Queries`,
				// `Unlimited runs`,
				`Multi-agent support`,
				`Marketplace integrations`,
				`3,900 credits/month`,
				`Priority support`,
			],
			isSeatBased: true,
			defaultUsers: 1,
			minUsers: 1,
			recommended: true,
		},
		enterprise: {
			name: 'Enterprise',
			features: [
				'Unlimited meetings & mins',
				'Unlimited Pro Queries',
				'Unlimited/custom integrations',
				'Marketplace integrations',
				'Early access to experimental features',
			],
			price: 'Custom',
			_id: 'enterprise-plan',
			plan: 'Enterprise',
			subscriptionType: '',
			monthlyPrice: 'Custom',
			yearlyPrice: 'Custom',
			currency: '',
			totalPrice: 'Custom',
			isSeatBasedPlan: true,
			contactSales: true,
		},
	},
	commonFeatures: [
		// 'Advanced user engagement analytics',
		// 'Integrate with 50+ apps',
		// 'Collaborate with 15 members',
		// 'AI-powered content generation',
		// 'Dedicated priority support',
		// 'Custom workspace branding',
		// '250GB secure cloud storage',
	],
};
