export const Actions = {
	SET_KNOWLEDGE_ASSISTANTS_LIST: 'SET_KNOWLEDGE_ASSISTANTS_LIST',
	SET_ACTIVE_KNOWLEDGE_ASSISTANT: 'SET_ACTIVE_KNOWLEDGE_ASSISTANT',
	SET_ALL_AI_PROMPTS: 'SET_ALL_AI_PROMPTS',
	SELECT_AI_PROMPT: 'SELECT_AI_PROMPT',
	SET_KNOWLEDGE_BASE_INFO: 'SET_KNOWLEDGE_BASE_INFO',
	UPDATE_CONTEXT_VALUES: 'UPDATE_CONTEXT_VALUES',
	SET_ACTIONS_INFO: 'SET_ACTIONS_INFO',
	GET_TRIGGERS: 'GET_TRIGGERS',
	DELETE_TRIGGER: 'DELETE_TRIGGER',
	CONNECT_TRIGGER: 'CONNECT_TRIGGER',
	SET_KNOWLEDGE_BASE_ACTIVE_FILE_STATUS: 'SET_KNOWLEDGE_BASE_ACTIVE_FILE_STATUS',
	SET_AGENTS_LIST_FOR_AUTOMATION: 'SET_AGENTS_LIST_FOR_AUTOMATION',
	SET_ACTIVE_ASSISTANT_FOR_AUTOMATION: 'SET_ACTIVE_ASSISTANT_FOR_AUTOMATION',
	SET_FETCHED_KNOWLEDGE_AGENTS: 'SET_FETCHED_KNOWLEDGE_AGENTS',

	RESET_STATE: 'RESET_STATE',
};
