export const Actions = {
	SET_KNOWLEDGE_ASSISTANTS_LIST: 'SET_KNOWLEDGE_ASSISTANTS_LIST',
	SET_ACTIVE_KNOWLEDGE_ASSISTANT: 'SET_ACTIVE_KNOWLEDGE_ASSISTANT',
	SET_ALL_AI_PROMPTS: 'SET_ALL_AI_PROMPTS',
	SELECT_AI_PROMPT: 'SELECT_AI_PROMPT',
	SET_KNOWLEDGE_BASE_INFO: 'SET_KNOWLEDGE_BASE_INFO',
	UPDATE_CONTEXT_VALUES: 'UPDATE_CONTEXT_VALUES',
	SET_ACTIONS_INFO: 'SET_ACTIONS_INFO',
	RESET_STATE: 'RESET_STATE',
};
