export const Actions = {
	GET_TENANT_GALLERIES: 'GET_TENANT_GALLERIES',
	GET_TENANT_ALBUMS: 'GET_TENANT_ALBUMS',
	GET_TAGS_LIST: 'GET_TAGS_LIST',
	POST_TAG_LIST: 'POST_TAG_LIST',
	GET_EDIT_PREFERENCES: 'GET_EDIT_PREFERENCES',
	GET_LAYOUT_SETTINGS: 'GET_LAYOUT_SETTINGS',
	GET_COLLABORATORS: 'GET_COLLABORATORS',
	GET_IMAGE_DUPLICATES: 'GET_IMAGE_DUPLICATES',
	GET_WATERMARKS_LIST: 'GET_WATERMARKS_LIST',
	RESET_STATE: 'RESET_STATE',
};
