//Action Type constant for login signup workspace settings APIs
export const TENANT_USER_LOGIN_SIGNUP_API = {
    url: '/tenant-user',
    login: '/login',
    verifyPassword: '/verify-password',
    signup: '/signup',
    signupRequest: '/signup-request',
    signupInvitedRequest: '/signup-invited-user',
    verifySignUpOTP: '/verify-signup-otp',
    resendOTP: '/resend-otp',
    signupInvitedUser: '/signup-invited-user',
    requestOTP: '/request-otp',
    verifyEmail: '/request-email-address-verification',
    forgotPassword: '/request-password-reset',
    verifyAccount: '/verify-email-address',
    loginWithPassword: '/login-with-password',
    verifyResetPassword: '/verify-password-reset',
    updatePassword: '/update-password',
    tenantUsers: '/tenant-users',
    tenantUsersList: '/tenant-users-list',
    workspace: '/accessible-tenants',
    subdomainAwail: '/workspaceId-availability?workspaceId=',
    set2FASettings: '/two-factor-authentication',
    get2FAStatus: '/two-factor-authentication-status',
    googleAuthenticator: '/google-authenticator',
    qrCode: '/qr-code',
    teamMembersFilters: '/tenantUserDefaultFilters',
};

export const LOVCO_TENANT_USER_LOGIN_SIGNUP_API = {
    signup: '/loveco/signup',

    verifyEmail: '/loveco/verify-signup-code',
    verifyLoginCode: '/loveco/verify-login-code',
    checkEmailAccountExists: '/account-with-email',
    myProfile: '/loveco/my-profile',
    registerTenant: '/loveco/register-tenant',
    lovecoSubscriptionPlans: '/loveco-subscription-plans',
};

export const LOVECO_TENANTS = {
    payments: '/payments',
    requestPaymentOrder: '/request-payment-order',
    brandDetails: '/brand-details',
    accountWithPhoneNumber: '/account-with-phone-number?phoneNumber=',
};

//Action Type constant for tenant.jsx file
export const TENANTS = {
    url: '/tenants/',
    accessibleTenants: '/accessible-tenants',
    accesstoken: '/access-token',
    accessControls: '/access-controls',
    preferences: '/preferences',
    subscriptionRecords: '/subscription-records',
    profile: '/profile',
    myProfile: '/my-profile',
    tenantUsers: '/tenant-users',
    tenantInvitations: '/tenant-invitations',
    role: '/role',
    createWorkspace: '/create-workspace',
    tenantUser: '/tenant-user',
    page: '?limit=15&page=',
    markRead: '/mark-all-read',
    businessName: '/business-name',
    websiteUrl: '/website-url',
    logos: '/logos',
    metaLogos: '/metaLogos',
    watermarks: '/watermarks',
    intercom: '/intercom',
    requestRazorPayOrder: '/request-payment-order',
    payments: '/payments',
    verifyPayment: '/verify-payment',
    subscriptionDetails: '/subscription-details',
    invoicePreferences: '/invoice-preferences',
    billingDetails: '/billingDetails',
    storageDetails: '/storage-details',
    variables: '/variables',
    workspaceAssets: '/workspaceAssets-images',
    socialMediaProfile: '/social-media-profile',
    address: '/address',
    contactDetails: '/contact-details',
    paymentStatus: '/order-payment-status',
    productivityData: '/productivity-data',
    productivityDataWeeklyData: '/weekly-productivity',
    productivityInsights: 'productivity-insights',
    usageDetails: '/usage-details',
    updateTenant: '/update-tenant-user',
    resendInvitation: '/tenant-invitations',
    billing: '/billing',
    subscriptions: '/subscriptions',
};
export const Proposals = {
    url: '/proposals',
    urlParam: '/',
    convertToProposal: '/convert-to-proposal',
    duplicateProposal: '/duplicate',
    createdAt: '?createdAt<',
    createdAtLt: '&createdAt<',
    createdAtGt: '&createdAt>',
    titleLt: '&title<',
    titleGt: '&title>',
    title: 'title=',
    status: '&status=',
    insights: '/proposal-insights',
    sort: '?sort=',
    versions: '/versions',
    accept: '/accept',
    reject: '/reject',
    search: '&search=',
    unmarkStatus: '/unmark-status',
    unlinkForm: '/form-response',
    expiry: '/mark-as-expired',
    templates: '/templates',
    page: '?page=',
    limit: '&limit=',
    sortBy: '&sortBy=',
    sortType: '&sortType=',
    startDate: '&startDate=',
    endDate: '&endDate=',
    weddingSummary: '/weddingDateSummary',
    summary: '/summary',
    eventDateSummary: 'firstEventDateSummary',
    eventsSummary: '/eventSummary',
    shareViaEmail: '/share-via-email',
};
export const Templates = {
    url: '/templates',
    urlParam: '/',
    createProposal: '/create-proposal',
};

//Galleries
export const GALLERIES = {
    url: '/galleries',
    slug: '/gallery-slug-availability/',
    albumSlug: '/album-slug-availability/',
    galleryUrlWithSlash: '/galleries/',
    albums: '/albums',
    userID: '?user_id=',
    details: '/details',
    preferences: '/preferences',
    sections: '/sections',
    detailed: '&detailed=',
    images: '/images',
    sortingField: '&sort=',
    pagination: '&pagination=',
    imageurl: '/gallery-images',
    versionID: '?versionId=',
    getShareDetails: '/share-details',
    coverImage: '/cover-image',
    changeMasterPin: '/change-master-access-pin',
    changeGuestPin: '/guest-access',
    suggestedEdits: '/suggested-edits',
    sortImages: '/custom-sort-order',
    giSuggestedEdits: '/gi-suggested-edits',
    isResolved: '?isResolved=',
    moveImages: '/move-images',
    collections: '/collections',
    galeryCollections: '/gallery-collections/',
    galleryDetailed: '?detailed=',
    Andpage: '&page=',
    page: '?page=',
    limit: '&limit=',
    sortType: '?sort=',
    checkDuplicates: '/check-duplicates',

    uploadDetails: '/upload-details',
    uploadStatus: '/upload-status',
    uploadBatchID: '?uploadBatchId=',

    sectionSortOrder: '/section-sort-order',
    pageLimit: '&pageLimit=',
    pageInfo: '/page-info',
    pageLmt: '?pageLimit=',

    imageFileNames: '/image-file-names',
    subscriptionPlans: '/subscription-plans',
    aiCreditsPlan: '/ai-credit-plans',
    clientGalleryVisitors: '/client-gallery-visitors',
    category: 'category=',
    visitorRole: 'visitorRole=',
    search: '&search=',
    createdAtLt: '&createdAt<',
    createdAtGt: '&createdAt>',
    firstName: '&firstName=',
    clientGalleryFilters: '/client-gallery-visitor-filters',
    download: '/download',
    galleryInsights: '/gallery-insights',
};

//Action Type constant for all API's of Project, Albums and images actions
export const PROJECTS = {
    url: '/projects/',
    projectsList: '/projects-list',
    albums: '/albums',
    galleries: '/galleries',
    images: '/images',
    projectDetails: '/info',
    updateDetails: '/update-details',
    updatePreferences: '/update-preferences',
    sortImages: '/update-custom-sort-order',
    invite: '/create-enduser-invitation',
    publicViewAccess: '/public-view-access',
    galleryID: 'gallery_id=',
    uploadImages: '/upload-images',
    addCollaborators: '/add-member',
    removeCollaborators: '/remove-member',
    changeMasterPin: '/change-master-access-pin',
    contentDistribution: '/content-distribution/get-credentials',
    albumID: '?album_id=',
    deleteAlbum: '/delete',
    galleryID: '?gallery_id=',
    createProject: '/create-project',
    userID: '?user_id=',
    coverImage: '/update-cover-image',
    moveImages: '/move-images',
    deleteIamge: '/delete-images',
    download: '/download',
    basicDetails: '/basic-details',
    searchImages: '/search-images',
    displayName: '?displayName=',
    layoutSettings: '/layout-settings',
};

//Action Type constant for all API's of Forms
export const FORMS = {
    url: '/forms',
    markActive: '/mark-active',
    markInactive: '/mark-inactive',
    duplicate: '/duplicate',
    responses: '/responses',
    responsesStats: '/stats',
    page: '?page=',
    andPage: '&page=',
    limit: '&limit=',
    title: '?title=',
};

export const NOTIFICATIONS = {
    url: '/notifications ',
};
