import { memo, useContext, useState, useEffect, useCallback, useMemo, useRef } from 'react';
import '../../../assets/scss/home_page/initialHomepage.scss';
import Context from '../../../context/context';
import { useNavigate } from 'react-router-dom';
import ProactiveSuggestions from './ProactiveSuggestions';
import ChatPrompts from './ChatPrompts';
import QuickActions from '../../components/globalComponents/QuickActions';
import GlobalWidget from '../../components/globalComponents/GlobalWidget';
import ChatBox from '../../components/chat/ChatBox';
import { message } from '../../components/globalComponents/CustomToast';
import { Tooltip } from 'antd';
import { ReactComponent as AgentsSvg } from '../../../assets/svg/sidebar/agentsIcon.svg';
import { ReactComponent as PromptsSvg } from '../../../assets/svg/home_page/prompts.svg';
import { ReactComponent as CalendarSvg } from '../../../assets/svg/home_page/calendar.svg';
import { ReactComponent as TaskSvg } from '../../../assets/svg/home_page/tasks.svg';
import { ReactComponent as ContactSvg } from '../../../assets/svg/home_page/contacts.svg';
import { ReactComponent as AutomationsSvg } from '../../../assets/svg/home_page/automation.svg';
import Suggestions from './Suggestions';

const optionsList = [
	{
		id: 1,
		label: 'Insights',
		value: 'proactiveSuggestions',
		tooltip: 'Insights generated by VEAI before you ask',
		showOption: false,
		icon: AgentsSvg,
	},
	{
		id: 2,
		label: 'Ask Me',
		value: 'prompts',
		tooltip: 'Ask anything from the prompts library',
		showOption: false,
		icon: PromptsSvg,
	},
	{
		id: 3,
		label: 'Calendar',
		value: 'calendar',
		tooltip: 'Manage your meetings and events',
		showOption: true,
		icon: CalendarSvg,
	},
	{
		id: 4,
		label: 'Task',
		value: 'task',
		tooltip: 'Manage your tasks and to-dos',
		showOption: true,
		icon: TaskSvg,
	},
	{
		id: 5,
		label: 'Contact',
		value: 'contact',
		tooltip: 'Manage your contacts and clients',
		controlValue: 'contact',
		showOption: true,
		icon: ContactSvg,
	},
	{
		id: 6,
		label: 'Automation',
		value: 'automation',
		tooltip: 'Create and manage your automations',
		controlValue: 'automation',
		showOption: true,
		icon: AutomationsSvg,
	},
];

const SuggestedOptions = [
	{
		id: 1,
		title: 'Event',
		value: 'event',
		action: ({ setInfo }) => {
			setInfo((prev) => ({ ...prev, openEventsPopup: true }));
		},
	},
	{
		id: 2,
		title: 'Session',
		value: 'session',
		action: ({ setInfo }) => {
			setInfo((prev) => ({ ...prev, openSessionPopup: true, dropdown: false }));
		},
	},
	{
		id: 3,
		title: 'Task',
		value: 'task',
		action: ({ setInfo }) => {
			setInfo((prev) => ({ ...prev, createTaskPopup: true }));
		},
	},
	{
		id: 4,
		title: 'Contact',
		value: 'contacts',
		action: ({ setInfo }) => {
			setInfo((prev) => ({ ...prev, openClientPopup: true }));
		},
	},
	{
		id: 5,
		title: 'Automation',
		value: 'automation',
		action: async ({ setInfo, navigate, createAutomation, info }) => {
			if (info?.isAutomationLoading) return;
			try {
				setInfo((prev) => ({
					...prev,
					showLoader: true,
					loaderMessage: 'Creating automation...',
				}));
				const response = await createAutomation({
					name: 'Untitled Automation',
					version: 1,
					steps: [],
					status: 'draft',
				});
				if (response?.[0]) {
					navigate(`/automation-builder/${response?.[1]?._id}`);
				} else {
					message.error('Failed to create automation');
				}
			} catch (error) {
				message.error('Failed to create automation');
			} finally {
				setInfo((prev) => ({
					...prev,
					showLoader: false,
					loaderMessage: '',
				}));
			}
		},
	},
];

const suggestions = [
	{
		id: 1,
		text: 'Innovations reshape healthcare, enhancing patient experiences with data.',
	},
	{
		id: 2,
		text: 'Breakthrough tech revolutionizes healthcare, leading to better outcomes.',
	},
	{
		id: 3,
		text: 'Innovative advancements enhance healthcare, driving better patient results.',
	},
	{
		id: 4,
		text: 'Tech changes healthcare, providing better outcomes through data.',
	},
	{
		id: 5,
		text: 'Next-gen tech alters healthcare, ensuring better patient results.',
	},
	{
		id: 6,
		text: 'Tech transforms healthcare, improving patient care with data.',
	},
	{
		id: 7,
		text: 'Pioneering tech reshapes healthcare, achieving better patient results.',
	},
];
const InitialHomePage = () => {
	const {
		templates: { updateStateValues, currentSessionId },
		profileInfo: { tenantUserAccessControls },
		aiSetup: { getPromptsData, promptsData },
		templates: { aiSuggestedPendingActions, getAISuggestedPendingActions },
	} = useContext(Context);

	const navigate = useNavigate();
	const timeoutIdRef = useRef(null);

	const [info, setInfo] = useState({
		selectedOption: '',
		options: optionsList,
		promptsCategory: 'all',
		optionsHandledOnce: Object?.values(optionsList)?.reduce((acc, option) => {
			acc[option.value] = false;
			return acc;
		}, {}),
		minimizedChatBox: true,
		minimizedChatBoxState: true,
		showSuggestions: false,
	});

	useEffect(() => {
		return () => {
			updateStateValues({ aiSuggestedPendingActions: null });
			clearTimeout(timeoutIdRef.current);
		};
	}, []);

	useEffect(() => {
		if (!promptsData) {
			// Always fetch if no data yet
			getPromptsData({ category: 'all', limit: 30 });
			return;
		}

		if (promptsData?.data?.length > 0) {
			if (!info?.optionsHandledOnce?.prompts) {
				handleUpdateOptions('prompts');
				setInfo((prev) => ({
					...prev,
					optionsHandledOnce: {
						...prev.optionsHandledOnce,
						prompts: true,
					},
				}));
			}
		} else {
			// Hide the option if no data
			setInfo((prev) => ({
				...prev,
				options: prev.options.map((o) =>
					o.value === 'prompts' ? { ...o, showOption: false } : o,
				),
			}));
		}
	}, [promptsData]);

	useEffect(() => {
		if (!aiSuggestedPendingActions) {
			getAISuggestedPendingActions(
				{
					page: 1,
					limit: 20,
					sortBy: 'createdAt',
					sortType: -1,
				},
				true,
			);
			return;
		}

		const cards = aiSuggestedPendingActions?.pendingActions?.filter(
			(card) => card?.title?.length > 0,
		);

		if (cards?.length > 0) {
			if (!info?.optionsHandledOnce?.proactiveSuggestions) {
				handleUpdateOptions('proactiveSuggestions');
				setInfo((prev) => ({
					...prev,
					optionsHandledOnce: {
						...prev.optionsHandledOnce,
						proactiveSuggestions: true,
					},
				}));
			}
		} else {
			setInfo((prev) => ({
				...prev,
				options: prev.options.map((o) =>
					o.value === 'proactiveSuggestions' ? { ...o, showOption: false } : o,
				),
			}));
		}
	}, [aiSuggestedPendingActions]);

	useEffect(() => {
		if (options?.length > 0 && !info?.selectedOption) {
			// Set the first visible option as the selected option
			setInfo((prev) => ({
				...prev,
				selectedOption: options[0]?.value,
			}));
		}
	}, [info?.selectedOption]);

	const handleContainerClick = useCallback(() => {
		if (info?.minimizedChatBox) return;

		setInfo((prev) => ({
			...prev,
			minimizedChatBox: true,
			showSuggestions: false,
		}));
		timeoutIdRef.current = setTimeout(() => {
			setInfo((prev) => ({
				...prev,
				minimizedChatBoxState: true,
			}));
		}, 300);
	}, [info?.minimizedChatBox]);

	const handleUpdateOptions = (value) => {
		let updatedOptions = info?.options;
		updatedOptions = updatedOptions?.map((option) => {
			if (option?.value === value) {
				option.showOption = true;
			}
			return option;
		});

		const selectedOption = updatedOptions?.find((option) => option?.showOption)?.value ?? '';

		setInfo((prev) => ({
			...prev,
			options: updatedOptions,
			selectedOption,
		}));
	};

	const handleOptionSelection = (option) => {
		if (info?.selectedOption === option?.value) {
			return;
		}

		setInfo((prev) => ({
			...prev,
			selectedOption: option?.value,
		}));
	};

	const renderedOptions = useMemo(() => {
		if (!tenantUserAccessControls || !info?.options) return null;

		const isAdmin = tenantUserAccessControls?.role === 'admin';

		const accessControlMap = Object.fromEntries(
			tenantUserAccessControls?.accessControls?.map((item) => [item?.app, item]) || [],
		);

		return info?.options?.map((option) => {
			if (!option?.showOption && !option?.controlValue) return null;

			if (option?.controlValue) {
				const accessControl = accessControlMap[option?.controlValue];
				const isEnabled = accessControl?.isEnabled;
				if (!isAdmin && !isEnabled) return null;
			}
			const Icon = option?.icon;
			return (
				<Tooltip
					key={option?.id}
					title={<div className="tooltipValue">{option?.tooltip}</div>}
					placement="bottom"
					arrow={false}
					trigger="hover"
					color={'transparent'}
					rootClassName="tooltip-wrapper"
				>
					<div
						className={`option ${
							info?.selectedOption === option?.value ? 'active' : ''
						}`}
						onClick={() => handleOptionSelection(option)}
					>
						<div className="option-label">
							<Icon />
							{option?.label}
						</div>
					</div>
				</Tooltip>
			);
		});
	}, [
		tenantUserAccessControls?.role,
		tenantUserAccessControls?.accessControls,
		info?.options,
		info?.selectedOption,
		handleOptionSelection, // make sure this is stable (e.g., memoized if needed)
	]);

	const handleCustomOnSendFunction = useCallback(
		(data) => {
			updateStateValues({ activePayloadForChat: data });
			navigate(`/chat/${currentSessionId}`);
		},
		[currentSessionId],
	);

	const updatePromptsCategory = (value) => {
		setInfo((prev) => ({
			...prev,
			promptsCategory: value,
		}));
	};

	const handleCustomChatBoxClick = (e) => {
		e?.stopPropagation();
		if (!info?.minimizedChatBox) return;
		setInfo((prev) => ({
			...prev,
			minimizedChatBox: false,
			minimizedChatBoxState: false,
			showSuggestions: true,
		}));
	};

	const componentMapper = useMemo(
		() => ({
			proactiveSuggestions: <ProactiveSuggestions />,
			prompts: <ChatPrompts promptsCategory={info?.promptsCategory} />,
			calendar: <GlobalWidget option={'calendar'} />,
			task: <GlobalWidget option={'task'} />,
			automation: <GlobalWidget option={'automation'} />,
			contact: <GlobalWidget option={'contacts'} />,
		}),
		[info?.promptsCategory],
	);

	const options = useMemo(
		() => info?.options?.filter((option) => option?.showOption),
		[info?.options],
	);

	return (
		<div
			className={`initial-home-page-container`}
			onClick={handleContainerClick}
			style={{
				...(options?.length === 0 && { justifyContent: 'center' }),
			}}
		>
			<div className="quick-actions-container">
				<QuickActions suggestedOptions={SuggestedOptions} />
			</div>
			<div
				className={`home-page-container-header `}
				style={{
					...(options?.length === 0 && { marginTop: 0 }),
				}}
			>
				<div className={`title-container `}>
					<div className="title-text">
						<h2 className="title-two">PROACTIVE</h2>
						<span className="title-one">Answers before you Ask!</span>

						{/* <span className="title-two">truly yours</span> */}
					</div>
					{/* <div className="sub-text">Answers before you Ask!</div> */}
				</div>
				<div
					className={`chatbox-wrapper ${
						!info?.minimizedChatBox ? 'expanded' : 'minimized'
					}`}
				>
					<div className={`chatbox-container `}>
						<ChatBox
							onSend={handleCustomOnSendFunction}
							customChatActions={true}
							autoFocus={false}
							animatePlaceholder={true}
							startPage={info?.minimizedChatBoxState}
							customChatBoxClick={handleCustomChatBoxClick}
						/>
					</div>
				</div>

				{!info?.showSuggestions && (
					<div className="options-container">{renderedOptions}</div>
				)}
			</div>
			{options?.length > 0 && !info?.showSuggestions && (
				<div className="home-page-container-content">
					{componentMapper[info?.selectedOption]}
				</div>
			)}

			{info?.showSuggestions && <Suggestions data={suggestions} />}
		</div>
	);
};

export default memo(InitialHomePage);
