import jwtDecode from 'jwt-decode';
import { memo, useContext, useState, useEffect, useCallback, useMemo, useRef } from 'react';
// import { Tooltip } from 'antd';
import { useNavigate } from 'react-router-dom';
import Context from '../../../context/context';
// import QuickActions from '../../components/globalComponents/QuickActions';
import { message } from '../../components/globalComponents/CustomToast';
// import AskMe from './AskMe';
// import GlobalWidget from '../../components/globalComponents/GlobalWidget';
// import ChatPrompts from './ChatPrompts';
import ProactiveSuggestions from './ProactiveSuggestions';
import '../../../assets/scss/home_page/initialHomepage.scss';
// import Spinner from '../../components/loaders/Spinner';
import { getGreeting } from '../../../helpers';
// import useWorkspaceMode from '../../hooks/useWorkspaceMode';

const optionsList = [
	// {
	//  id: 0,
	//  label: 'Ask',
	//  value: 'ask',
	//  tooltip: 'Ask anything',
	//  showOption: true,
	//  icon: VeSvg
	// },
	// {
	//  id: 1,
	//  label: 'Proactive',
	//  value: 'proactiveSuggestions',
	//  tooltip: 'Insights generated by VEAI before you ask',
	//  showOption: false,
	//  icon: AgentsSvg,
	// },
	// 'All',
	// {
	//  id: 2,
	//  label: 'Suggested prompts',
	//  value: 'prompts',
	//  tooltip: 'Ask anything from the prompts library',
	//  showOption: false,
	//  icon: PromptsSvg,
	// },
	// {
	//  id: 3,
	//  label: 'Calendar',
	//  value: 'calendar',
	//  tooltip: 'Manage your meetings and events',
	//  showOption: true,
	//  icon: CalendarSvg,
	// },
	// {
	//  id: 4,
	//  label: 'Task',
	//  value: 'task',
	//  tooltip: 'Manage your tasks and to-dos',
	//  showOption: true,
	//  icon: TaskSvg,
	// },
	// {
	//  id: 5,
	//  label: 'Contact',
	//  value: 'contact',
	//  tooltip: 'Manage your contacts and clients',
	//  controlValue: 'contact',
	//  showOption: true,
	//  icon: ContactSvg,
	// },
	// {
	//  id: 6,
	//  label: 'Automation',
	//  value: 'automation',
	//  tooltip: 'Create and manage your automations',
	//  controlValue: 'automation',
	//  showOption: true,
	//  icon: AutomationsSvg,
	// },
];

const SuggestedOptions = [
	{
		id: 1,
		title: 'Event',
		value: 'event',
		action: ({ setInfo }) => {
			setInfo((prev) => ({ ...prev, openEventsPopup: true }));
		},
	},
	{
		id: 2,
		title: 'Schedule',
		value: 'schedule',
		action: ({ setInfo }) => {
			setInfo((prev) => ({ ...prev, openSchedulerDrawer: true, dropdown: false }));
		},
	},
	{
		id: 3,
		title: 'Task',
		value: 'task',
		action: ({ setInfo }) => {
			setInfo((prev) => ({ ...prev, createTaskPopup: true }));
		},
	},
	{
		id: 4,
		title: 'Contact',
		value: 'contacts',
		action: ({ setInfo }) => {
			setInfo((prev) => ({ ...prev, openClientPopup: true }));
		},
	},
	{
		id: 5,
		title: 'Automation',
		value: 'automation',
		action: async ({ setInfo, navigate, createAutomation, info }) => {
			if (info?.isAutomationLoading) return;
			try {
				setInfo((prev) => ({
					...prev,
					showLoader: true,
					loaderMessage: 'Creating automation...',
				}));
				const response = await createAutomation({
					name: 'Untitled Automation',
					version: 1,
					steps: [],
					status: 'draft',
				});
				if (response?.[0]) {
					navigate(`/automation-builder/${response?.[1]?._id}`);
				} else {
					message.error('Failed to create automation');
				}
			} catch (error) {
				message.error('Failed to create automation');
			} finally {
				setInfo((prev) => ({
					...prev,
					showLoader: false,
					loaderMessage: '',
				}));
			}
		},
	},
];

const homePageTextContent = {
	ask: {
		title: 'Own your memory',
		subText: 'Your enterprise knowledge hub for instant answers.',
	},
	proactiveSuggestions: {
		title: 'Answers before you ask',
		subText: 'Insights delivered before you even think to ask. the power of proactive memory.',
	},
	prompts: {
		title: 'Ask anything from the prompts library',
		subText: 'Your enterprise knowledge hub for instant answers.',
	},
	calendar: {
		title: "Let's make every moment count",
		subText: "More than a schedule - It's your daily mission control",
	},
	task: {
		title: 'Transform goals into actionable tasks',
		subText: 'Clear steps. Smart prioritisation. No more to-do overwhelm',
	},
	contact: {
		title: 'Stay connected with who matters',
		subText: 'Your most relevant contacts, surfaced when you need them most.',
	},
	automation: {
		title: 'Automate the routine, focus on what matters',
		subText: 'Trigger workflows, reduce busywork, and stay in flow.',
	},
};

const InitialHomePage = () => {
	const {
		templates: { updateStateValues, aiSuggestedPendingActions, getAISuggestedPendingActions },
		profileInfo: { userDetailsData, aiCategories, getAiCategories },
		aiSetup: { getPromptsData, promptsData },
	} = useContext(Context);

	const navigate = useNavigate();
	const timeoutIdRef = useRef(null);
	const previousSelectedOptionRef = useRef(null);

	const [info, setInfo] = useState({
		selectedOption: '',
		options: optionsList,
		promptsCategory: 'all',
		optionsHandledOnce: Object.values(optionsList).reduce((acc, option) => {
			acc[option.value] = false;
			return acc;
		}, {}),
		aiSuggestionsModalOpen: false,
	});

	useEffect(() => {
		return () => {
			updateStateValues({ aiSuggestedPendingActions: null });
			clearTimeout(timeoutIdRef.current);
		};
	}, []);

	// useEffect(() => {
	// 	if (!aiCategories) {
	// 		getAiCategoriesOptions();
	// 	}
	// }, [aiCategories, info?.options, aiSuggestedPendingActions]);

	// const getAiCategoriesOptions = async () => {
	// 	const response = await getAiCategories();
	// 	if (response?.[0] === true) {
	// 		setInfo((prev) => ({
	// 			...prev,
	// 			options: [...optionsList, ...response?.[1]],
	// 		}));
	// 	}
	// };

	useEffect(() => {
		if (info?.aiSuggestionsModalOpen) {
			updateStateValues({
				leftSidebarState: 'close',
			});
		}
	}, [info?.aiSuggestionsModalOpen]);

	useEffect(() => {
		if (!promptsData) {
			getPromptsData({ category: 'all', limit: 30, page: 1 });
			return;
		}
		if (promptsData?.data?.length > 0) {
			if (!info?.optionsHandledOnce?.prompts) {
				handleUpdateOptions('prompts');
				setInfo((prev) => ({
					...prev,
					optionsHandledOnce: { ...prev.optionsHandledOnce, prompts: true },
				}));
			}
		} else {
			setInfo((prev) => ({
				...prev,
				options: prev.options.map((o) =>
					o.value === 'prompts' ? { ...o, showOption: false } : o,
				),
			}));
		}
	}, [promptsData]);

	// useEffect(() => {
	// 	if (!aiSuggestedPendingActions) {
	// 		getAISuggestedPendingActions(
	// 			{
	// 				page: 1,
	// 				limit: 20,
	// 				sortBy: 'createdAt',
	// 				sortType: -1,
	// 			},
	// 			true,
	// 		);
	// 		return;
	// 	}
	// 	const cards = aiSuggestedPendingActions?.pendingActions?.filter(
	// 		(card) => card?.title?.length > 0,
	// 	);
	// 	if (cards?.length > 0) {
	// 		if (!info?.optionsHandledOnce?.proactiveSuggestions) {
	// 			handleUpdateOptions('proactiveSuggestions');
	// 			setInfo((prev) => ({
	// 				...prev,
	// 				optionsHandledOnce: { ...prev.optionsHandledOnce, proactiveSuggestions: true },
	// 			}));
	// 		}
	// 	} else {
	// 		setInfo((prev) => ({
	// 			...prev,
	// 			options: prev.options.map((o) =>
	// 				o.value === 'proactiveSuggestions' ? { ...o, showOption: false } : o,
	// 			),
	// 		}));
	// 	}
	// }, [aiSuggestedPendingActions]);

	const handleUpdateOptions = (value) => {
		let updatedOptions = info?.options;
		updatedOptions = updatedOptions?.map((option) => {
			if (option?.value === value) {
				option.showOption = true;
			}
			return option;
		});
		const selectedOption = updatedOptions?.find((option) => option?.showOption)?.value ?? '';
		setInfo((prev) => ({
			...prev,
			options: updatedOptions,
			selectedOption,
		}));
	};

	const handleOptionSelection = (option) => {
		if (info?.selectedOption === option) {
			return;
		}
		previousSelectedOptionRef.current = info?.selectedOption;
		setInfo((prev) => ({
			...prev,
			selectedOption: option,
		}));
	};

	const renderedOptions = useMemo(() => {
		return info?.options?.map((option) => {
			return (
				<div
					className={`option ${info?.selectedOption === option ? 'active' : ''}`}
					onClick={(e) => {
						e.stopPropagation();
						handleOptionSelection(option);
					}}
					key={option}
				>
					<div className="option-label">{option}</div>
				</div>
			);
		});
	}, [info?.options, info?.selectedOption]);

	const updatePromptsCategory = (value) => {
		setInfo((prev) => ({
			...prev,
			promptsCategory: value,
		}));
	};

	const options = useMemo(
		() => info?.options?.filter((option) => option?.showOption),
		[info?.options],
	);

	const handleModalOpen = useCallback((value) => {
		setInfo((prev) => {
			if (prev?.aiSuggestionsModalOpen === value) return prev;
			return {
				...prev,
				aiSuggestionsModalOpen: value,
			};
		});
	}, []);

	const title = homePageTextContent[info?.selectedOption]?.title || '';
	const subText = homePageTextContent[info?.selectedOption]?.subText || '';
	const userName =
		jwtDecode(localStorage.getItem('usertoken'))?.userName ||
		userDetailsData?.firstName + ' ' + (userDetailsData?.lastName ?? '') ||
		'User';
	const greeting = getGreeting();

	return (
		<div className="initial-home-page-wrapper">
			<div
				className={`initial-home-page-container ${
					info?.aiSuggestionsModalOpen ? 'initial-page-active' : ''
				}`}
				style={{
					...(options?.length === 0 && { justifyContent: 'center' }),
					// width: info?.aiSuggestionsModalOpen ? 'calc(100% - 700px)' : '100%',
				}}
			>
				{/* <div className="quick-actions-container">
				<QuickActions suggestedOptions={SuggestedOptions} />
			</div> */}
				<div
					className={`home-page-container-header `}
					// style={{
					// 	...(options?.length === 0 && { marginTop: 0 }),
					// }}
				>
					<div className={`title-container `}>
						<div className="title-text">
							<h2 className="title-one">{greeting}!</h2>
							<span className="title-two">{userName}</span>
						</div>
					</div>
					{
						!info?.showSuggestions && ''
						// <div className="options-wrapper">
						// 	<div className={`homepage__options-container`}>{renderedOptions}</div>
						// 	{/* <div className="arrow-container">
						// 		{showArrows.left && (
						// 			<div
						// 				className="arrow left-arrow"
						// 				onClick={() => handleScroll('left')}
						// 			>
						// 				<ChevronRightThinSvg style={{ transform: 'rotate(180deg)' }} />
						// 			</div>
						// 		)}
						// 		{showArrows.right && (
						// 			<div
						// 				className="arrow right-arrow"
						// 				onClick={() => handleScroll('right')}
						// 			>
						// 				<ChevronRightThinSvg />
						// 			</div>
						// 		)}
						// 	</div> */}
						// </div>
					}
				</div>

				<div className="home-page-container-content">
					{/* {info?.selectedOption === 'All' ? (
						<ProactiveSuggestions
							option={info?.selectedOption}
							previousOption={previousSelectedOptionRef.current}
						/>
					) : (
						<GlobalWidget option={info?.selectedOption} />
					)} */}
					<ProactiveSuggestions
						option={info?.selectedOption}
						previousOption={previousSelectedOptionRef.current}
						handleModalOpen={handleModalOpen}
					/>
				</div>
			</div>
		</div>
	);
};

export default memo(InitialHomePage);
