export const Actions = {
	GET_TENANT_SETTINGS: 'GET_TENANT_SETTINGS',
	GET_USER_DETAILS: 'GET_USER_DETAILS',
	GET_TENANT_USER_DETAILS: 'GET_TENANT_USER_DETAILS',
	GET_2FA_QR_CODE: 'GET_2FA_QR_CODE',
	SET_2FA_SETTINGS: 'SET_2FA_SETTINGS',
	GET_USER_WORKSPACE_LIST: 'GET_USER_WORKSPACE_LIST',
};
