export const CALENDAR = {
	// calendarChat: '/calendar_chat',
	calendarChat: '/multi_agent_chat',
	sendEventToAi: '/calendar_event_classify',
	calendarEventsList: '/calendar/getEventsList',
	calendarAllEvents: '/calendar/getAllEvents',
	createCalendarEvent: '/calendar/createEvent',
	createCalendarCategory: '/calendar/createCalendarCategory',
	updateCalendarCategory: '/calendar/updateCalendarCategory',
	calendarCategories: '/calendar/getCalendarCategories',
	deleteCalendarCategory: '/calendar/deleteCalendarCategory',
	getCalendarEventDetails: '/calendar/getEvent',
	updateCalendarEvent: '/calendar/updateEvent',
	deleteCalendarEvent: '/calendar/deleteEvent',
	resetCalendarState: 'RESET_CALENDAR_STATE',
	resetCalendarAiChat: 'RESET_CALENDAR_AI_CHAT',
};
