export const Actions = {
	GET_CALENDAR_CHAT: 'GET_CALENDAR_CHAT',
	GET_CALENDAR_EVENTS_LIST: 'GET_CALENDAR_EVENTS_LIST',
	CREATE_CALENDAR_EVENT: 'CREATE_CALENDAR_EVENT',
	CREATE_CALENDAR_CATEGORY: 'CREATE_CALENDAR_CATEGORY',
	UPDATE_CALENDAR_CATEGORY: 'UPDATE_CALENDAR_CATEGORY',
	GET_CALENDAR_CATEGORIES: 'GET_CALENDAR_CATEGORIES',
	DELETE_CALENDAR_CATEGORY: 'DELETE_CALENDAR_CATEGORY',
	RESET_CALENDAR_STATE: 'RESET_CALENDAR_STATE',
};
