export const Actions = {
	GET_CALENDAR_CHAT: 'GET_CALENDAR_CHAT',
	GET_CALENDAR_EVENTS_LIST: 'GET_CALENDAR_EVENTS_LIST',
	CREATE_CALENDAR_EVENT: 'CREATE_CALENDAR_EVENT',
	RESET_CALENDAR_STATE: 'RESET_CALENDAR_STATE',
};
