export const PromptData = [
	{
		id: 1,
		title: '💬 Turn That Thought Into a Meeting',
		prompt: "Create a calendar invite titled '[Meeting Title]' with [Participants] on [Date] at [Time], and include this agenda: [Agenda].",
		variables: ['Meeting Title', 'Participants', 'Date', 'Time', 'Agenda'],
		type: 'calendar',
		priority: 10,
		dept: ['general'],
	},
	{
		id: 2,
		title: '⚡ Lock In Your Daily Power Hour',
		prompt: "Block a daily deep work session titled 'Power Hour' at [Preferred Time] on [Days] focused on [Focus Area], and mark it as a distraction-free event.",
		variables: ['Preferred Time', 'Days', 'Focus Area'],
		type: 'calendar',
		priority: 9,
		dept: ['productivity'],
	},
	{
		id: 3,
		title: '🎯 Make Space for Your Weekly Goal',
		prompt: "Schedule focused calendar blocks to achieve '[Goal Title]' by [Deadline], allocating approximately [Estimated Hours Needed] over the week.",
		variables: ['Goal Title', 'Estimated Hours Needed', 'Deadline'],
		type: 'calendar',
		priority: 9,
		dept: ['strategy', 'planning'],
	},
	{
		id: 4,
		title: '🧠 Upgrade Next Week with Smart Flow',
		prompt: 'Review the past week based on [Work Preferences], [Time Constraints], and [Focus Priorities], then suggest a new calendar flow for better alignment.',
		variables: ['Work Preferences', 'Time Constraints', 'Focus Priorities'],
		type: 'calendar',
		priority: 8,
		dept: ['planning'],
	},
	{
		id: 5,
		title: '📝 Break Down Your Goal into Actionable Tasks',
		prompt: "Create a task titled '[Task Title]' with a [Due Date], assign it to [Assignee], set the priority to [Priority Level], and categorize it under [Category].",
		variables: ['Task Title', 'Due Date', 'Assignee', 'Priority Level', 'Category'],
		type: 'task',
		priority: 10,
		dept: ['operations', 'project management'],
	},
	{
		id: 6,
		title: '📅 Plan Your Week with a Task Sprint',
		prompt: 'Generate a task sprint for this week with [Task Titles] assigned to [Team Members], prioritized by [Priority], and spread across [Days].',
		variables: ['Task Titles', 'Team Members', 'Priority', 'Days'],
		type: 'task',
		priority: 9,
		dept: ['team management'],
	},
	{
		id: 7,
		title: '🎯 Set Milestones for a New Project',
		prompt: 'Create milestone tasks titled [Milestone Titles] for the project [Project Name], each assigned to [Owner] and due by [Deadline].',
		variables: ['Milestone Titles', 'Project Name', 'Owner', 'Deadline'],
		type: 'task',
		priority: 9,
		dept: ['strategy'],
	},
	{
		id: 8,
		title: '🔁 Convert Repeating Work into Recurring Tasks',
		prompt: "Create a recurring task titled '[Task Title]' to be done every [Frequency] by [Assignee], with priority [Priority Level].",
		variables: ['Task Title', 'Frequency', 'Assignee', 'Priority Level'],
		type: 'task',
		priority: 8,
		dept: ['operations'],
	},
	{
		id: 9,
		title: '📇 Add a New Contact with Full Context',
		prompt: 'Add a new contact named [Full Name] with email [Email], phone number [Phone Number], and tag them as a [Contact Type] from [Source].',
		variables: ['Full Name', 'Email', 'Phone Number', 'Contact Type', 'Source'],
		type: 'contacts',
		priority: 10,
		dept: ['crm', 'sales'],
	},
	{
		id: 10,
		title: '🔗 Enrich and Categorize Your Network',
		prompt: 'Update contact [Full Name] with new information including [Company Name], [Role], and label them as [Client/Lead/Partner].',
		variables: ['Full Name', 'Company Name', 'Role', 'Client/Lead/Partner'],
		type: 'contacts',
		priority: 9,
		dept: ['crm'],
	},
	{
		id: 11,
		title: '🧠 Tag Contacts for Smarter Segmentation',
		prompt: 'Apply tags like [Tags] to contact [Full Name] based on their behavior, source, or status in the sales cycle.',
		variables: ['Full Name', 'Tags'],
		type: 'contacts',
		priority: 8,
		dept: ['sales', 'marketing'],
	},
	{
		id: 12,
		title: '📌 Follow Up with a High-Priority Contact',
		prompt: 'Create a follow-up reminder for [Full Name] scheduled on [Date] with context: [Note/Reason].',
		variables: ['Full Name', 'Date', 'Note/Reason'],
		type: 'contacts',
		priority: 9,
		dept: ['crm'],
	},
	{
		id: 13,
		title: '🤖 Trigger a Follow-Up After Form Submission',
		prompt: 'Create an automation that triggers when a form is submitted and sends a follow-up email to [Email], waits [Delay Time], and assigns a task to [Assignee].',
		variables: ['Email', 'Delay Time', 'Assignee'],
		type: 'automation',
		priority: 10,
		dept: ['workflow'],
	},
	{
		id: 14,
		title: '📬 Auto-Send Reminders for Upcoming Events',
		prompt: 'Set up an automation that checks for events happening in the next [Time Range] and sends reminder emails to [Attendees] with message: [Reminder Text].',
		variables: ['Time Range', 'Attendees', 'Reminder Text'],
		type: 'automation',
		priority: 9,
		dept: ['operations'],
	},
	{
		id: 15,
		title: '🔄 Auto-Create Tasks from New Contacts',
		prompt: "Set an automation that creates a task titled '[Task Title]' every time a new contact of type [Contact Type] is added, assigned to [Team Member].",
		variables: ['Task Title', 'Contact Type', 'Team Member'],
		type: 'automation',
		priority: 8,
		dept: ['sales', 'workflow'],
	},
	{
		id: 16,
		title: '🧠 Route New Leads to the Right Owner',
		prompt: "Set an automation that checks incoming contact source as [Lead Source] and assigns the contact to [Owner] with a task titled '[Follow-Up Task]'.",
		variables: ['Lead Source', 'Owner', 'Follow-Up Task'],
		type: 'automation',
		priority: 9,
		dept: ['sales'],
	},
];
