export const PromptData = [
	{
		id: 1,
		title: 'Create Tailored Wedding Photography Proposals',
		prompt: "Generate a personalized proposal for [client_name]'s wedding at [venue_name] with details on packages, timing, and add-ons.",
		variables: ['Client Name', 'Venue Name', 'Event Date', 'Packages'],
		type: ['task'],
		priority: 10,
		dept: ['sales'],
		workspaceType: ['photography'],
	},
	{
		id: 2,
		title: 'Recommend Camera Settings Based on Conditions',
		prompt: 'Suggest optimal camera settings for [shoot_type] in [lighting_conditions].',
		variables: ['Shoot Type', 'Lighting Conditions'],
		type: ['action'],
		priority: 10,
		dept: ['operations'],
		workspaceType: ['photography'],
	},
	{
		id: 3,
		title: 'Enhance Event Photography Edits',
		prompt: 'Suggest editing styles to enhance photos from [event_type].',
		variables: ['Event Type'],
		type: ['action'],
		priority: 10,
		dept: ['operations'],
		workspaceType: ['photography'],
	},
	{
		id: 4,
		title: 'Develop Portrait Lighting Techniques',
		prompt: 'Generate creative lighting setups for portrait shoots at [location].',
		variables: ['Location'],
		type: ['action'],
		priority: 9,
		dept: ['operations'],
		workspaceType: ['photography'],
	},
	{
		id: 5,
		title: 'Design Stunning Mood Boards',
		prompt: 'Create a mood board for a [theme] photoshoot featuring [client_style] preferences.',
		variables: ['Theme', 'Client Style'],
		type: ['action'],
		priority: 9,
		dept: ['marketing'],
		workspaceType: ['photography'],
	},
	{
		id: 6,
		title: 'Personalize Instagram Captions',
		prompt: 'Write engaging captions for [number] posts about [shoot_type].',
		variables: ['Number of Posts', 'Shoot Type'],
		type: ['task'],
		priority: 9,
		dept: ['marketing'],
		workspaceType: ['photography'],
	},
	{
		id: 7,
		title: 'Create Custom Photo Albums',
		prompt: "Design a custom photo album layout for [client_name]'s [event_type].",
		variables: ['Client Name', 'Event Type'],
		type: ['task'],
		priority: 9,
		dept: ['operations'],
		workspaceType: ['photography'],
	},
	{
		id: 11,
		title: 'Upsell Services via AI Suggestions',
		prompt: 'What additional services can be offered to [client_name] for their [event_type]?',
		variables: ['Client Name', 'Event Type'],
		type: ['action'],
		priority: 8,
		dept: ['sales'],
		workspaceType: ['photography'],
	},
	{
		id: 12,
		title: 'Client Communication Email Drafts',
		prompt: 'Write a follow-up email to [client_name] about [specific_topic].',
		variables: ['Client Name', 'Topic'],
		type: ['task'],
		priority: 8,
		dept: ['sales'],
		workspaceType: ['photography'],
	},
	{
		id: 13,
		title: 'Generate Client Feedback Form',
		prompt: "Draft a feedback form tailored to [client_name]'s [event_type].",
		variables: ['Client Name', 'Event Type'],
		type: ['task'],
		priority: 8,
		dept: ['operations'],
		workspaceType: ['photography'],
	},
	{
		id: 16,
		title: 'Suggest Destination Photography Locations',
		prompt: 'Suggest beautiful locations for destination shoots in [region].',
		variables: ['Region'],
		type: ['action'],
		priority: 7,
		dept: ['marketing'],
		workspaceType: ['photography'],
	},
	{
		id: 18,
		title: 'Optimize Website Portfolio Layouts',
		prompt: 'Redesign [portfolio_section] for better client engagement.',
		variables: ['Portfolio Section'],
		type: ['task'],
		priority: 7,
		dept: ['marketing'],
		workspaceType: ['photography'],
	},
	{
		id: 19,
		title: 'Create Photography FAQs',
		prompt: 'Generate a FAQ list for [services_offered].',
		variables: ['Services Offered'],
		type: ['task'],
		priority: 7,
		dept: ['operations'],
		workspaceType: ['photography'],
	},
	{
		id: 20,
		title: 'Draft Testimonial Requests',
		prompt: 'Write a testimonial request email for [client_name].',
		variables: ['Client Name'],
		type: ['task'],
		priority: 7,
		dept: ['marketing'],
		workspaceType: ['photography'],
	},
	{
		id: 22,
		title: 'Plan Seasonal Photography Offers',
		prompt: 'Suggest promotional offers for [season] targeting [audience_type].',
		variables: ['Season', 'Audience Type'],
		type: ['task'],
		priority: 7,
		dept: ['marketing'],
		workspaceType: ['photography'],
	},
	{
		id: 23,
		title: 'Identify High-Performing Marketing Campaigns',
		prompt: 'Analyze past marketing campaigns and recommend the most successful strategies.',
		variables: ['Campaign Data'],
		type: ['task'],
		priority: 7,
		dept: ['marketing'],
		workspaceType: ['photography'],
	},
	{
		id: 28,
		title: 'Design Social Media Content Calendar',
		prompt: 'Create a 30-day social media content plan for [platform] promoting [services].',
		variables: ['Platform', 'Services'],
		type: ['task'],
		priority: 6,
		dept: ['marketing'],
		workspaceType: ['photography'],
	},
	{
		id: 29,
		title: 'Create Photography Contracts',
		prompt: 'Draft a customizable contract template for [event_type] services.',
		variables: ['Event Type'],
		type: ['task'],
		priority: 6,
		dept: ['operations'],
		workspaceType: ['photography'],
	},
	{
		id: 30,
		title: 'Generate Photography Blog Ideas',
		prompt: 'Suggest engaging blog topics about [photography_type] for [target_audience].',
		variables: ['Photography Type', 'Target Audience'],
		type: ['task'],
		priority: 6,
		dept: ['marketing'],
		workspaceType: ['photography'],
	},
	{
		id: 34,
		title: 'Generate Unique Photoshoot Concepts',
		prompt: 'Suggest innovative ideas for a [theme]-themed shoot.',
		variables: ['Theme'],
		type: ['action'],
		priority: 5,
		dept: ['operations'],
		workspaceType: ['photography'],
	},
	{
		id: 35,
		title: 'Recommend Photo Composition Techniques',
		prompt: 'Suggest unique photo compositions for [shoot_type].',
		variables: ['Shoot Type'],
		type: ['action'],
		priority: 5,
		dept: ['operations'],
		workspaceType: ['photography'],
	},
	{
		id: 36,
		title: 'Automate Invoicing Design',
		prompt: 'Create a professional invoice template for [service_type] packages.',
		variables: ['Service Type'],
		type: ['task'],
		priority: 5,
		dept: ['operations'],
		workspaceType: ['photography'],
	},
	{
		id: 38,
		title: 'Create Inspirational Quote Graphics',
		prompt: 'Generate inspirational quote designs for [platform].',
		variables: ['Platform'],
		type: ['task'],
		priority: 4,
		dept: ['marketing'],
		workspaceType: ['photography'],
	},
	{
		id: 39,
		title: 'Generate Personalized Thank-You Notes',
		prompt: 'Draft a thank-you note for [client_name] after [event_type].',
		variables: ['Client Name', 'Event Type'],
		type: ['task'],
		priority: 4,
		dept: ['sales'],
		workspaceType: ['photography'],
	},
	{
		id: 40,
		title: 'Draft Pre-Event Checklists',
		prompt: 'Create a detailed checklist for [event_type] photoshoots.',
		variables: ['Event Type'],
		type: ['task'],
		priority: 3,
		dept: ['operations'],
		workspaceType: ['photography'],
	},
	{
		id: 41,
		title: 'Analyze Website Engagement Metrics',
		prompt: 'Provide insights into engagement on [website_section].',
		variables: ['Website Section'],
		type: ['task'],
		priority: 3,
		dept: ['marketing'],
		workspaceType: ['photography'],
	},
	{
		id: 42,
		title: 'Suggest Stock Photo Opportunities',
		prompt: 'Identify trending stock photo topics for [industry].',
		variables: ['Industry'],
		type: ['action'],
		priority: 3,
		dept: ['marketing'],
		workspaceType: ['photography'],
	},
	{
		id: 43,
		title: 'Develop Caption Themes for the Month',
		prompt: 'Generate theme-based captions for [platform] posts.',
		variables: ['Platform'],
		type: ['task'],
		priority: 2,
		dept: ['marketing'],
		workspaceType: ['photography'],
	},
	{
		id: 44,
		title: 'Recommend Marketing Keywords',
		prompt: 'Suggest high-ranking SEO keywords for [services_offered].',
		variables: ['Services Offered'],
		type: ['task'],
		priority: 2,
		dept: ['marketing'],
		workspaceType: ['photography'],
	},
	{
		id: 45,
		title: 'Create a New User Guide',
		prompt: 'Draft a comprehensive onboarding guide for new clients.',
		variables: [],
		type: ['task'],
		priority: 1,
		dept: ['operations'],
		workspaceType: ['photography'],
	},
];
