export const Actions = {
	GET_SMART_FILE_ACTIVITY_SUCCESS: 'GET_SMART_FILE_ACTIVITY_SUCCESS',
	GET_SMART_FILE_VIEWERS_SUCCESS: 'GET_SMART_FILE_VIEWERS_SUCCESS',
	GET_VIEWERS_SESSION_DETAILS_SUCCESS: 'GET_VIEWERS_SESSION_DETAILS_SUCCESS',
	RESET_ACTIVITY_STATE: 'RESET_ACTIVITY_STATE',
};
