// for initial state themeContext
export const initialThemeState = {
	activeTheme: 'theme1',
	id: 'theme1',
	name: 'Classic Times Roman',
	source: 've',
	category: 'Professional',
	isDesktopMobileFontLinked: true,
	colors: {
		background: '#ffffff',
		background2: '#ffffff',
		text: {
			h1: {
				color: '#111111',
			},
			h2: {
				color: '#111111',
			},
			h3: {
				color: '#111111',
			},
			h4: {
				color: '#111111',
			},
			h5: {
				color: '#111111',
			},
			h6: {
				color: '#111111',
			},
			p: {
				color: '#111111',
			},
			span: {
				color: '#111111',
			},
		},
		shape: {
			color: '#797979',
		},
		buttons: {
			primary: {
				normal: {
					background: '#ffffff',
					color: '#111111',
					borderColor: '#111111',
				},
				hover: {
					background: '#11111',
					color: '#ffffff',
					borderColor: '#ffffff',
				},
			},
			secondary: {
				normal: {
					background: '#FFFFFF',
					color: '#111111',
					borderColor: '#111111',
				},
				hover: {
					background: '#ffffff',
					color: '#111111',
					borderColor: '#111111',
				},
			},
			tertiary: {
				normal: {
					background: 'transparent',
					color: '#111111',
					border: 'none',
				},
				hover: {
					color: '#111111',
					border: 'none',
				},
			},
		},
		form: {
			inputQuestion: {
				color: '#111111',
				borderColor: '#111111',
				background: '#ffffff',
			},
			inputDescription: {
				color: '#111111',
				borderColor: '#111111',
				background: '#ffffff',
			},
			submitButton: {
				background: '#111111',
				color: '#ffffff',
				borderColor: '#ffffff',
			},
			inputAnswer: {
				color: '#111111',
				borderColor: '#111111',
			},
			formHeading: {
				color: '#111111',
				borderColor: '#111111',
				background: '#ffffff',
			},
			formDescription: {
				color: '#111111',
				borderColor: '#111111',
				background: '#ffffff',
			},
		},
		event: {
			eventTitle: {
				color: '#111111',
			},
		},
	},
	fonts: {
		h1: {
			activeFontID: '66f2b1919870deb1cc6ece9a',
			fontFamily: 'Times New Roman, Times, serif',
			fontSize: '42px',
			fontWeight: 700,
			lineHeight: 1.1,
			letterSpacing: '5px',
			fontStyle: 'normal',
			activeVariant: 2,
		},
		h2: {
			activeFontID: '66f2b1919870deb1cc6ece9a',
			fontFamily: 'Times New Roman, Times, serif',
			fontSize: '30px',
			fontWeight: 700,
			lineHeight: 1,
			letterSpacing: '0px',
			fontStyle: 'normal',
			activeVariant: 2,
		},
		h3: {
			activeFontID: '66f2b1919870deb1cc6ece9a',
			fontFamily: 'Times New Roman, Times, serif',
			fontSize: '24px',
			fontWeight: 700,
			lineHeight: 1,
			letterSpacing: '0px',
			fontStyle: 'normal',
			activeVariant: 2,
		},
		h4: {
			activeFontID: '66f2b1919870deb1cc6ece9a',
			fontFamily: 'Times New Roman, Times, serif',
			fontSize: '20px',
			fontWeight: 700,
			lineHeight: 1,
			letterSpacing: '0px',
			fontStyle: 'normal',
			activeVariant: 2,
		},
		h5: {
			activeFontID: '66f2b1919870deb1cc6ece9a',
			fontFamily: 'Times New Roman, Times, serif',
			fontSize: '18px',
			fontWeight: 700,
			lineHeight: 1,
			letterSpacing: '0px',
			fontStyle: 'normal',
			activeVariant: 2,
		},
		h6: {
			activeFontID: '66f2b1919870deb1cc6ece9a',
			fontFamily: 'Times New Roman, Times, serif',
			fontSize: '16px',
			fontWeight: 700,
			lineHeight: 1,
			letterSpacing: '0px',
			fontStyle: 'normal',
			activeVariant: 2,
		},
		p: {
			activeFontID: '66f2b1919870deb1cc6ece92',
			fontFamily: 'Verdana, Geneva, sans-serif',
			fontSize: '18px',
			fontWeight: 400,
			lineHeight: 1,
			letterSpacing: '0px',
			activeVariant: 0,
			fontStyle: 'normal',
		},
		span: {
			activeFontID: '66f2b1919870deb1cc6ece92',
			fontFamily: 'Verdana, Geneva, sans-serif',
			fontSize: '18px',
			fontWeight: 400,
			lineHeight: 1,
			letterSpacing: '0px',
			activeVariant: 0,
			fontStyle: 'normal',
		},
		buttons: {
			primary: {
				activeFontID: '66f2b1919870deb1cc6ece92',
				fontFamily: 'Verdana, Geneva, sans-serif',
				fontSize: '14px',
				fontWeight: 400,
				lineHeight: 1,
				letterSpacing: '0px',
				activeVariant: 0,
				fontStyle: 'normal',
			},
			secondary: {
				activeFontID: '66f2b1919870deb1cc6ece92',
				fontFamily: 'Verdana, Geneva, sans-serif',
				fontSize: '14px',
				fontWeight: 400,
				lineHeight: 1,
				letterSpacing: '0px',
				activeVariant: 0,
				fontStyle: 'normal',
			},
			tertiary: {
				activeFontID: '66f2b1919870deb1cc6ece92',
				fontFamily: 'Verdana, Geneva, sans-serif',
				fontSize: '14px',
				fontWeight: 400,
				lineHeight: 1,
				letterSpacing: '0px',
				activeVariant: 0,
				fontStyle: 'normal',
			},
		},
		form: {
			inputQuestion: {
				activeFontID: '66f2b1919870deb1cc6ece92',
				fontFamily: 'Verdana, Geneva, sans-serif',
				fontSize: '16px',
				fontWeight: 400,
				lineHeight: 1,
				letterSpacing: '0px',
			},
			inputDescription: {
				activeFontID: '66f2b1919870deb1cc6ece92',
				fontFamily: 'Verdana, Geneva, sans-serif',
				fontSize: '16px',
				fontWeight: 400,
				lineHeight: 1,
				letterSpacing: '0px',
			},
			submitButton: {
				activeFontID: '66f2b1919870deb1cc6ece92',
				fontFamily: 'Verdana, Geneva, sans-serif',
				fontSize: '16px',
				fontWeight: 400,
				lineHeight: 1,
				letterSpacing: '0px',
			},
			inputAnswer: {
				activeFontID: '66f2b1919870deb1cc6ece92',
				fontFamily: 'Verdana, Geneva, sans-serif',
				fontSize: '16px',
				fontWeight: 400,
				lineHeight: 1,
				letterSpacing: '0px',
			},
			formHeading: {
				activeFontID: '66f2b1919870deb1cc6ece92',
				fontFamily: 'Verdana, Geneva, sans-serif',
				fontSize: '16px',
				fontWeight: 400,
				lineHeight: 1,
				letterSpacing: '0px',
			},
			formDescription: {
				activeFontID: '66f2b1919870deb1cc6ece92',
				fontFamily: 'Verdana, Geneva, sans-serif',
				fontSize: '16px',
				fontWeight: 400,
				lineHeight: 1,
				letterSpacing: '0px',
			},
		},
		event: {
			eventTitle: {
				activeFontID: '66f2b1919870deb1cc6ece92',
				fontFamily: 'Verdana, Geneva, sans-serif',
				fontSize: '18px',
				fontWeight: 400,
				lineHeight: 1,
				letterSpacing: '0px',
				activeVariant: 0,
				fontStyle: 'normal',
			},
		},
	},
	mobileFonts: {
		h1: {
			fontSize: '29px',
		},
		h2: {
			fontSize: '24px',
		},
		h3: {
			fontSize: '20px',
		},
		h4: {
			fontSize: '18px',
		},
		h5: {
			fontSize: '16px',
		},
		h6: {
			fontSize: '14px',
		},
		p: {
			fontSize: '16px',
		},
		span: {
			fontSize: '16px',
		},
		event: {
			eventTitle: {
				fontSize: '14px',
			},
		},
	},
	buttons: {
		buttonType: 'primary',
		primary: {
			buttonShape: 'rounded',
			normal: {
				borderRadius: '20px',
				borderWidth: '1px',
				borderStyle: 'solid',
				paddingTop: '12px',
				paddingBottom: '12px',
				paddingRight: '18px',
				paddingLeft: '18px',
			},
			hover: {
				background: '#123047',
				borderColor: '#123047',
			},
		},
		secondary: {
			buttonShape: 'rounded',
			normal: {
				borderRadius: '16px',
				borderWidth: '2px',
				borderStyle: 'solid',
				paddingTop: '12px',
				paddingBottom: '12px',
				paddingRight: '16px',
				paddingLeft: '16px',
			},
			hover: {
				background: '#F5F8FA',
				borderColor: '#123047',
			},
		},
		tertiary: {
			buttonShape: 'rounded',
			normal: {
				borderRadius: '0px',
				borderWidth: '0px',
				borderStyle: 'none',
				paddingTop: '12px',
				paddingBottom: '12px',
				paddingRight: '16px',
				paddingLeft: '16px',
			},
			hover: {
				color: '#123047',
				border: 'none',
			},
		},
	},
	layout: {},
};

// for themes list
export const ThemesListJson = [
	// professional
	{
		id: 'theme1',
		name: 'Classic Times Roman',
		source: 've',
		category: 'Professional',
		isDesktopMobileFontLinked: true,
		colors: {
			background: '#ffffff',
			background2: '#ffffff',
			text: {
				h1: {
					color: '#111111',
				},
				h2: {
					color: '#111111',
				},
				h3: {
					color: '#111111',
				},
				h4: {
					color: '#111111',
				},
				h5: {
					color: '#111111',
				},
				h6: {
					color: '#111111',
				},
				p: {
					color: '#111111',
				},
				span: {
					color: '#111111',
				},
			},
			shape: {
				color: '#797979',
			},
			buttons: {
				primary: {
					normal: {
						background: '#ffffff',
						color: '#111111',
						borderColor: '#111111',
					},
					hover: {
						background: '#11111',
						color: '#ffffff',
						borderColor: '#ffffff',
					},
				},
				secondary: {
					normal: {
						background: '#FFFFFF',
						color: '#111111',
						borderColor: '#111111',
					},
					hover: {
						background: '#ffffff',
						color: '#111111',
						borderColor: '#111111',
					},
				},
				tertiary: {
					normal: {
						background: 'transparent',
						color: '#111111',
						border: 'none',
					},
					hover: {
						color: '#111111',
						border: 'none',
					},
				},
			},
			form: {
				inputQuestion: {
					color: '#111111',
					borderColor: '#111111',
					background: '#ffffff',
				},
				inputDescription: {
					color: '#111111',
					borderColor: '#111111',
					background: '#ffffff',
				},
				submitButton: {
					background: '#111111',
					color: '#ffffff',
					borderColor: '#ffffff',
				},
				inputAnswer: {
					color: '#111111',
					borderColor: '#111111',
				},
				formHeading: {
					color: '#111111',
					borderColor: '#111111',
					background: '#ffffff',
				},
				formDescription: {
					color: '#111111',
					borderColor: '#111111',
					background: '#ffffff',
				},
			},
			event: {
				eventTitle: {
					color: '#111111',
				},
			},
		},
		fonts: {
			h1: {
				activeFontID: '66f2b1919870deb1cc6ece9a',
				fontFamily: 'Times New Roman, Times, serif',
				fontSize: '42px',
				fontWeight: 700,
				lineHeight: 1.1,
				letterSpacing: '5px',
				fontStyle: 'normal',
				activeVariant: 2,
			},
			h2: {
				activeFontID: '66f2b1919870deb1cc6ece9a',
				fontFamily: 'Times New Roman, Times, serif',
				fontSize: '30px',
				fontWeight: 700,
				lineHeight: 1,
				letterSpacing: '0px',
				fontStyle: 'normal',
				activeVariant: 2,
			},
			h3: {
				activeFontID: '66f2b1919870deb1cc6ece9a',
				fontFamily: 'Times New Roman, Times, serif',
				fontSize: '24px',
				fontWeight: 700,
				lineHeight: 1,
				letterSpacing: '0px',
				fontStyle: 'normal',
				activeVariant: 2,
			},
			h4: {
				activeFontID: '66f2b1919870deb1cc6ece9a',
				fontFamily: 'Times New Roman, Times, serif',
				fontSize: '20px',
				fontWeight: 700,
				lineHeight: 1,
				letterSpacing: '0px',
				fontStyle: 'normal',
				activeVariant: 2,
			},
			h5: {
				activeFontID: '66f2b1919870deb1cc6ece9a',
				fontFamily: 'Times New Roman, Times, serif',
				fontSize: '18px',
				fontWeight: 700,
				lineHeight: 1,
				letterSpacing: '0px',
				fontStyle: 'normal',
				activeVariant: 2,
			},
			h6: {
				activeFontID: '66f2b1919870deb1cc6ece9a',
				fontFamily: 'Times New Roman, Times, serif',
				fontSize: '16px',
				fontWeight: 700,
				lineHeight: 1,
				letterSpacing: '0px',
				fontStyle: 'normal',
				activeVariant: 2,
			},
			p: {
				activeFontID: '66f2b1919870deb1cc6ece92',
				fontFamily: 'Verdana, Geneva, sans-serif',
				fontSize: '18px',
				fontWeight: 400,
				lineHeight: 1,
				letterSpacing: '0px',
				activeVariant: 0,
				fontStyle: 'normal',
			},
			span: {
				activeFontID: '66f2b1919870deb1cc6ece92',
				fontFamily: 'Verdana, Geneva, sans-serif',
				fontSize: '18px',
				fontWeight: 400,
				lineHeight: 1,
				letterSpacing: '0px',
				activeVariant: 0,
				fontStyle: 'normal',
			},
			buttons: {
				primary: {
					activeFontID: '66f2b1919870deb1cc6ece92',
					fontFamily: 'Verdana, Geneva, sans-serif',
					fontSize: '14px',
					fontWeight: 400,
					lineHeight: 1,
					letterSpacing: '0px',
					activeVariant: 0,
					fontStyle: 'normal',
				},
				secondary: {
					activeFontID: '66f2b1919870deb1cc6ece92',
					fontFamily: 'Verdana, Geneva, sans-serif',
					fontSize: '14px',
					fontWeight: 400,
					lineHeight: 1,
					letterSpacing: '0px',
					activeVariant: 0,
					fontStyle: 'normal',
				},
				tertiary: {
					activeFontID: '66f2b1919870deb1cc6ece92',
					fontFamily: 'Verdana, Geneva, sans-serif',
					fontSize: '14px',
					fontWeight: 400,
					lineHeight: 1,
					letterSpacing: '0px',
					activeVariant: 0,
					fontStyle: 'normal',
				},
			},
			form: {
				inputQuestion: {
					activeFontID: '66f2b1919870deb1cc6ece92',
					fontFamily: 'Verdana, Geneva, sans-serif',
					fontSize: '16px',
					fontWeight: 400,
					lineHeight: 1,
					letterSpacing: '0px',
				},
				inputDescription: {
					activeFontID: '66f2b1919870deb1cc6ece92',
					fontFamily: 'Verdana, Geneva, sans-serif',
					fontSize: '16px',
					fontWeight: 400,
					lineHeight: 1,
					letterSpacing: '0px',
				},
				submitButton: {
					activeFontID: '66f2b1919870deb1cc6ece92',
					fontFamily: 'Verdana, Geneva, sans-serif',
					fontSize: '16px',
					fontWeight: 400,
					lineHeight: 1,
					letterSpacing: '0px',
				},
				inputAnswer: {
					activeFontID: '66f2b1919870deb1cc6ece92',
					fontFamily: 'Verdana, Geneva, sans-serif',
					fontSize: '16px',
					fontWeight: 400,
					lineHeight: 1,
					letterSpacing: '0px',
				},
				formHeading: {
					activeFontID: '66f2b1919870deb1cc6ece92',
					fontFamily: 'Verdana, Geneva, sans-serif',
					fontSize: '16px',
					fontWeight: 400,
					lineHeight: 1,
					letterSpacing: '0px',
				},
				formDescription: {
					activeFontID: '66f2b1919870deb1cc6ece92',
					fontFamily: 'Verdana, Geneva, sans-serif',
					fontSize: '16px',
					fontWeight: 400,
					lineHeight: 1,
					letterSpacing: '0px',
				},
			},
			event: {
				eventTitle: {
					activeFontID: '66f2b1919870deb1cc6ece92',
					fontFamily: 'Verdana, Geneva, sans-serif',
					fontSize: '18px',
					fontWeight: 400,
					lineHeight: 1,
					letterSpacing: '0px',
					activeVariant: 0,
					fontStyle: 'normal',
				},
			},
		},
		mobileFonts: {
			h1: {
				fontSize: '29px',
			},
			h2: {
				fontSize: '24px',
			},
			h3: {
				fontSize: '20px',
			},
			h4: {
				fontSize: '18px',
			},
			h5: {
				fontSize: '16px',
			},
			h6: {
				fontSize: '14px',
			},
			p: {
				fontSize: '16px',
			},
			span: {
				fontSize: '16px',
			},
			event: {
				eventTitle: {
					fontSize: '14px',
				},
			},
		},
		buttons: {
			buttonType: 'primary',
			primary: {
				buttonShape: 'rounded',
				normal: {
					borderRadius: '20px',
					borderWidth: '1px',
					borderStyle: 'solid',
					paddingTop: '12px',
					paddingBottom: '12px',
					paddingRight: '18px',
					paddingLeft: '18px',
				},
				hover: {
					background: '#123047',
					borderColor: '#123047',
				},
			},
			secondary: {
				buttonShape: 'rounded',
				normal: {
					borderRadius: '16px',
					borderWidth: '2px',
					borderStyle: 'solid',
					paddingTop: '12px',
					paddingBottom: '12px',
					paddingRight: '16px',
					paddingLeft: '16px',
				},
				hover: {
					background: '#F5F8FA',
					borderColor: '#123047',
				},
			},
			tertiary: {
				buttonShape: 'rounded',
				normal: {
					borderRadius: '0px',
					borderWidth: '0px',
					borderStyle: 'none',
					paddingTop: '12px',
					paddingBottom: '12px',
					paddingRight: '16px',
					paddingLeft: '16px',
				},
				hover: {
					color: '#123047',
					border: 'none',
				},
			},
		},
		layout: {},
	},
	{
		id: 'theme2',
		name: 'Modern Minimal VE Theme',
		source: 've',
		category: 'Professional',
		isDesktopMobileFontLinked: true,
		colors: {
			background: '#ffffff',
			background2: '#ffffff',
			text: {
				h1: { color: '#000000' },
				h2: { color: '#111111' },
				h3: { color: '#333333' },
				h4: { color: '#333333' },
				h5: { color: '#333333' },
				h6: { color: '#333333' },
				p: { color: '#555555' },
				span: { color: '#555555' },
			},
			shape: {
				color: '#F2F2F3',
			},
			buttons: {
				primary: {
					normal: {
						background: '#F2F2F3',
						color: '#0C0C0D',
						borderColor: '#0C0C0D',
					},
					hover: {},
				},
				secondary: {
					normal: {
						background: '#0C0C0D',
						color: '#F2F2F3',
						borderColor: '#F2F2F3',
					},
					hover: {},
				},
				tertiary: {
					normal: {
						background: 'transparent',
						color: '#F2F2F3',
						border: 'none',
					},
					hover: {},
				},
			},
			form: {
				inputQuestion: {
					color: '#0C0C0D',
					borderColor: '#0C0C0D',
				},
				inputDescription: {
					color: '#0C0C0D',
					borderColor: '#0C0C0D',
				},
				submitButton: {
					background: '#F2F2F3',
					color: '#0C0C0D',
					borderColor: '#0C0C0D',
				},
				inputAnswer: {
					color: '#0C0C0D',
					borderColor: '#0C0C0D',
				},
				formHeading: {
					color: '#0C0C0D',
					borderColor: '#0C0C0D',
				},
				formDescription: {
					color: '#0C0C0D',
					borderColor: '#0C0C0D',
				},
			},
			event: {
				eventTitle: {
					color: '#0C0C0D',
				},
			},
		},
		fonts: {
			h1: {
				activeFontID: '66f2b1919870deb1cc6ece81',
				fontFamily: 'Courier, monospace',
				fontSize: '42px',
				fontWeight: 700,
				lineHeight: 1,
				letterSpacing: '0px',
				fontStyle: 'normal',
				activeVariant: 2,
			},
			h2: {
				activeFontID: '66f2b1919870deb1cc6ece81',
				fontFamily: 'Courier, monospace',
				fontSize: '30px',
				fontWeight: 700,
				lineHeight: 1,
				letterSpacing: '0px',
				fontStyle: 'normal',
				activeVariant: 2,
			},
			h3: {
				activeFontID: '66f2b1919870deb1cc6ece81',
				fontFamily: 'Courier, monospace',
				fontSize: '24px',
				fontWeight: 700,
				lineHeight: 1,
				letterSpacing: '0px',
				fontStyle: 'normal',
				activeVariant: 2,
			},
			h4: {
				activeFontID: '66f2b1919870deb1cc6ece81',
				fontFamily: 'Courier, monospace',
				fontSize: '20px',
				fontWeight: 700,
				lineHeight: 1,
				fontStyle: 'normal',
				activeVariant: 2,
			},
			h5: {
				activeFontID: '66f2b1919870deb1cc6ece81',
				fontFamily: 'Courier, monospace',
				fontSize: '18px',
				fontWeight: 700,
				lineHeight: 1,
				fontStyle: 'normal',
				activeVariant: 2,
			},
			h6: {
				activeFontID: '66f2b1919870deb1cc6ece81',
				fontFamily: 'Courier, monospace',
				fontSize: '16px',
				fontWeight: 700,
				lineHeight: 1,
				fontStyle: 'normal',
				activeVariant: 2,
			},
			p: {
				activeFontID: '66f2b1919870deb1cc6ece81',
				fontFamily: 'Courier, monospace',
				fontSize: '16px',
				fontWeight: 400,
				lineHeight: 1,
				letterSpacing: '0px',
				fontStyle: 'normal',
				activeVariant: 0,
			},
			span: {
				activeFontID: '66f2b1919870deb1cc6ece81',
				fontFamily: 'Courier, monospace',
				fontSize: '16px',
				fontWeight: 400,
				lineHeight: 1,
				letterSpacing: '0px',
				fontStyle: 'normal',
				activeVariant: 0,
			},
			buttons: {
				primary: {
					fontFamily: 'Inter',
					fontSize: '14px',
					fontStyle: 'normal',
					fontWeight: 500,
					lineHeight: '20px',
				},
				secondary: {
					fontFamily: 'Inter',
					fontSize: '14px',
					fontStyle: 'normal',
					fontWeight: 500,
					lineHeight: '20px',
				},
				tertiary: {
					fontFamily: 'Inter',
					fontSize: '14px',
					fontStyle: 'normal',
					fontWeight: 500,
					lineHeight: '20px',
				},
			},
			form: {
				inputQuestion: {
					activeFontID: '66f2b1919870deb1cc6ece81',
					fontFamily: 'Courier, monospace',
					fontSize: '16px',
					fontWeight: 400,
					lineHeight: 1,
					letterSpacing: '0px',
				},
				inputDescription: {
					activeFontID: '66f2b1919870deb1cc6ece81',
					fontFamily: 'Courier, monospace',
					fontSize: '16px',
					fontWeight: 400,
					lineHeight: 1,
					letterSpacing: '0px',
				},
				submitButton: {
					activeFontID: '66f2b1919870deb1cc6ece81',
					fontFamily: 'Courier, monospace',
					fontSize: '16px',
					fontWeight: 400,
					lineHeight: 1,
					letterSpacing: '0px',
				},
				inputAnswer: {
					activeFontID: '66f2b1919870deb1cc6ece81',
					fontFamily: 'Courier, monospace',
					fontSize: '16px',
					fontWeight: 400,
					lineHeight: 1,
					letterSpacing: '0px',
				},
				formHeading: {
					activeFontID: '66f2b1919870deb1cc6ece81',
					fontFamily: 'Courier, monospace',
					fontSize: '16px',
					fontWeight: 400,
					lineHeight: 1,
					letterSpacing: '0px',
				},
				formDescription: {
					activeFontID: '66f2b1919870deb1cc6ece81',
					fontFamily: 'Courier, monospace',
					fontSize: '16px',
					fontWeight: 400,
					lineHeight: 1,
					letterSpacing: '0px',
				},
			},
			event: {
				eventTitle: {
					activeFontID: '66f2b1919870deb1cc6ece81',
					fontFamily: 'Courier, monospace',
					fontSize: '16px',
					fontWeight: 400,
					lineHeight: 1,
					letterSpacing: '0px',
				},
			},
		},
		mobileFonts: {
			h1: {
				fontSize: '28px',
			},
			h2: {
				fontSize: '24px',
			},
			h3: {
				fontSize: '20px',
			},
			h4: {
				fontSize: '18px',
			},
			h5: {
				fontSize: '16px',
			},
			h6: {
				fontSize: '14px',
			},
			p: {
				fontSize: '14px',
			},
			span: {
				fontSize: '14px',
			},
			event: {
				eventTitle: {
					fontSize: '14px',
				},
			},
		},
		buttons: {
			buttonType: 'primary',
			primary: {
				buttonShape: 'pill',
				normal: {
					borderRadius: '24px',
					borderWidth: '0px',
					borderStyle: 'solid',
					paddingTop: '12px',
					paddingBottom: '12px',
					paddingRight: '16px',
					paddingLeft: '16px',
				},
				hover: {},
			},
			secondary: {
				buttonShape: 'pill',
				normal: {
					borderRadius: '8px',
					borderWidth: '2px',
					borderStyle: 'solid',
					paddingTop: '12px',
					paddingBottom: '12px',
					paddingRight: '16px',
					paddingLeft: '16px',
				},
				hover: {},
			},
			tertiary: {
				buttonShape: 'pill',
				normal: {
					borderRadius: '0px',
					borderWidth: '0px',
					borderStyle: 'none',
					paddingTop: '12px',
					paddingBottom: '12px',
					paddingRight: '16px',
					paddingLeft: '16px',
				},
				hover: {},
			},
		},
		layout: {},
	},
	{
		id: 'theme3',
		name: 'Sophisticated Blue VE Theme',
		source: 've',
		category: 'Professional',
		isDesktopMobileFontLinked: true,
		colors: {
			background: '#F5F8FA',
			background2: '#F5F8FA',
			text: {
				h1: { color: '#1A3A57' },
				h2: { color: '#2E4E6C' },
				h3: { color: '#466680' },
				h4: { color: '#5C7A94' },
				h5: { color: '#708BA8' },
				h6: { color: '#849EC0' },
				p: { color: '#5C7A94' },
				span: { color: '#5C7A94' },
			},
			shape: {
				color: '#1A3A57',
			},

			buttons: {
				primary: {
					normal: {
						background: '#1A3A57',
						color: '#FFFFFF',
						borderColor: '#1A3A57',
					},
					hover: {
						background: '#123047',
						color: '#FFFFFF',
						borderColor: '#123047',
					},
				},
				secondary: {
					normal: {
						background: '#FFFFFF',
						color: '#1A3A57',
						borderColor: '#1A3A57',
					},
					hover: {
						background: '#F5F8FA',
						color: '#123047',
						borderColor: '#123047',
					},
				},
				tertiary: {
					normal: {
						background: 'transparent',
						color: '#1A3A57',
						border: 'none',
					},
					hover: {
						color: '#123047',
						border: 'none',
					},
				},
			},
			form: {
				inputQuestion: {
					color: '#1A3A57',
					borderColor: '#1A3A57',
				},
				inputDescription: {
					color: '#1A3A57',
					borderColor: '#1A3A57',
				},
				submitButton: {
					background: '#1A3A57',
					color: '#5C7A94',
					borderColor: '#1A3A57',
				},
				inputAnswer: {
					color: '#1A3A57',
					borderColor: '#1A3A57',
				},
				formHeading: {
					color: '#1A3A57',
					borderColor: '#1A3A57',
				},
				formDescription: {
					color: '#1A3A57',
					borderColor: '#1A3A57',
				},
			},
			event: {
				eventTitle: {
					color: '#FFFFFF',
				},
			},
		},
		fonts: {
			h1: {
				activeFontID: '66f2b1919870deb1cc6ece89',
				fontFamily: 'Futura, sans-serif',
				fontSize: '36px',
				fontWeight: 700,
				lineHeight: 1,
				letterSpacing: '0px',
			},
			h2: {
				activeFontID: '66f2b1919870deb1cc6ece89',
				fontFamily: 'Futura, sans-serif',
				fontSize: '30px',
				fontWeight: 600,
				lineHeight: 1,
				letterSpacing: '0px',
			},
			h3: {
				activeFontID: '66f2b1919870deb1cc6ece89',
				fontFamily: 'Futura, sans-serif',
				fontSize: '24px',
				fontWeight: 500,
				lineHeight: 1,
				letterSpacing: '0px',
			},
			h4: {
				activeFontID: '66f2b1919870deb1cc6ece89',
				fontFamily: 'Futura, sans-serif',
				fontSize: '20px',
				fontWeight: 400,
				lineHeight: 1,
				letterSpacing: '0px',
			},
			h5: {
				activeFontID: '66f2b1919870deb1cc6ece89',
				fontFamily: 'Futura, sans-serif',
				fontSize: '18px',
				fontWeight: 400,
				lineHeight: 1,
				letterSpacing: '0px',
			},
			h6: {
				activeFontID: '66f2b1919870deb1cc6ece89',
				fontFamily: 'Futura, sans-serif',
				fontSize: '16px',
				fontWeight: 400,
				lineHeight: 1,
				letterSpacing: '0px',
			},
			p: {
				activeFontID: '66f2b1919870deb1cc6ece89',
				fontFamily: 'Futura, sans-serif',
				fontSize: '16px',
				fontWeight: 400,
				lineHeight: 1,
				letterSpacing: '0px',
			},
			span: {
				activeFontID: '66f2b1919870deb1cc6ece89',
				fontFamily: 'Futura, sans-serif',
				fontSize: '16px',
				fontWeight: 400,
				lineHeight: 1,
				letterSpacing: '0px',
			},
			buttons: {
				primary: {
					fontFamily: 'Source Sans Pro, sans-serif',
					fontSize: '14px',
					fontStyle: 'normal',
					fontWeight: 600,
					lineHeight: 1,
				},
				secondary: {
					fontFamily: 'Source Sans Pro, sans-serif',
					fontSize: '14px',
					fontStyle: 'normal',
					fontWeight: 600,
					lineHeight: 1,
				},
				tertiary: {
					fontFamily: 'Source Sans Pro, sans-serif',
					fontSize: '14px',
					fontStyle: 'normal',
					fontWeight: 600,
					lineHeight: 1,
				},
			},
			form: {
				inputQuestion: {
					activeFontID: '66f2b1919870deb1cc6ece89',
					fontFamily: 'Futura, sans-serif',
					fontSize: '16px',
					fontWeight: 400,
					lineHeight: 1,
					letterSpacing: '0px',
				},
				inputDescription: {
					activeFontID: '66f2b1919870deb1cc6ece89',
					fontFamily: 'Futura, sans-serif',
					fontSize: '16px',
					fontWeight: 400,
					lineHeight: 1,
					letterSpacing: '0px',
				},
				submitButton: {
					activeFontID: '66f2b1919870deb1cc6ece89',
					fontFamily: 'Futura, sans-serif',
					fontSize: '16px',
					fontWeight: 400,
					lineHeight: 1,
					letterSpacing: '0px',
				},
				inputAnswer: {
					activeFontID: '66f2b1919870deb1cc6ece89',
					fontFamily: 'Futura, sans-serif',
					fontSize: '16px',
					fontWeight: 400,
					lineHeight: 1,
					letterSpacing: '0px',
				},
				formHeading: {
					activeFontID: '66f2b1919870deb1cc6ece89',
					fontFamily: 'Futura, sans-serif',
					fontSize: '16px',
					fontWeight: 400,
					lineHeight: 1,
					letterSpacing: '0px',
				},
				formDescription: {
					activeFontID: '66f2b1919870deb1cc6ece89',
					fontFamily: 'Futura, sans-serif',
					fontSize: '16px',
					fontWeight: 400,
					lineHeight: 1,
					letterSpacing: '0px',
				},
			},
			event: {
				eventTitle: {
					activeFontID: '66f2b1919870deb1cc6ecebf',
					fontFamily: 'amsterdam-two, cursive',
					fontSize: '18px',
					fontWeight: 400,
					lineHeight: 1,
					letterSpacing: '0px',
				},
			},
		},
		mobileFonts: {
			h1: {
				fontSize: '28px',
			},
			h2: {
				fontSize: '24px',
			},
			h3: {
				fontSize: '20px',
			},
			h4: {
				fontSize: '18px',
			},
			h5: {
				fontSize: '16px',
			},
			h6: {
				fontSize: '14px',
			},
			p: {
				fontSize: '14px',
			},
			span: {
				fontSize: '14px',
			},
			event: {
				eventTitle: {
					fontSize: '14px',
				},
			},
		},
		buttons: {
			buttonType: 'primary',
			primary: {
				buttonShape: 'rounded',
				normal: {
					borderRadius: '20px',
					borderWidth: '1px',
					borderStyle: 'solid',
					paddingTop: '12px',
					paddingBottom: '12px',
					paddingRight: '18px',
					paddingLeft: '18px',
				},
				hover: {
					background: '#123047',
					borderColor: '#123047',
				},
			},
			secondary: {
				buttonShape: 'rounded',
				normal: {
					borderRadius: '16px',
					borderWidth: '2px',
					borderStyle: 'solid',
					paddingTop: '12px',
					paddingBottom: '12px',
					paddingRight: '16px',
					paddingLeft: '16px',
				},
				hover: {
					background: '#F5F8FA',
					borderColor: '#123047',
				},
			},
			tertiary: {
				buttonShape: 'rounded',
				normal: {
					borderRadius: '0px',
					borderWidth: '0px',
					borderStyle: 'none',
					paddingTop: '12px',
					paddingBottom: '12px',
					paddingRight: '16px',
					paddingLeft: '16px',
				},
				hover: {
					color: '#123047',
					border: 'none',
				},
			},
		},
		layout: {},
	},

	// playfull
	{
		id: 'theme4',
		name: ' Quiche Sans Playful',
		source: 've',
		category: 'Playfull',
		isDesktopMobileFontLinked: true,
		colors: {
			background: '#463f3a',
			background2: '#463f3a',
			text: {
				h1: {
					color: '#f4f3ee',
				},
				h2: {
					color: '#f4f3ee',
				},
				h3: {
					color: '#f4f3ee',
				},
				h4: {
					color: '#f4f3ee',
				},
				h5: {
					color: '#f4f3ee',
				},
				h6: {
					color: '#f4f3ee',
				},
				p: {
					color: '#f4f3ee',
				},
				span: {
					color: '#f4f3ee',
				},
			},
			shape: {
				color: '#8a817c',
			},
			buttons: {
				primary: {
					normal: {
						background: '#bcb8b1',
						color: '#f4f3ee',
						borderColor: '#f4f3ee',
					},
					hover: {
						background: '#f4f3ee',
						color: '#bcb8b1',
						borderColor: '#bcb8b1',
					},
				},
				secondary: {
					normal: {
						background: '#bcb8b1',
						color: '#f4f3ee',
						borderColor: '#f4f3ee',
					},
					hover: {
						background: '#f4f3ee',
						color: '#bcb8b1',
						borderColor: '#bcb8b1',
					},
				},
				tertiary: {
					normal: {
						background: 'transparent',
						color: '#f4f3ee',
						border: 'none',
					},
					hover: {
						color: '#f4f3ee',
						border: 'none',
					},
				},
			},
			form: {
				inputQuestion: {
					color: '#f4f3ee',
					borderColor: '#463f3a',
					background: '#463f3a',
				},
				inputDescription: {
					color: '#f4f3ee',
					borderColor: '#463f3a',
					background: '#463f3a',
				},
				submitButton: {
					background: '#f4f3ee',
					color: '#463f3a',
					borderColor: '#463f3a',
				},
				inputAnswer: {
					background: '#f4f3ee',
					color: '#463f3a',
					borderColor: '#463f3a',
				},
				formHeading: {
					color: '#f4f3ee',
					borderColor: '#463f3a',
					background: '#463f3a',
				},
				formDescription: {
					color: '#f4f3ee',
					borderColor: '#463f3a',
					background: '#463f3a',
				},
			},
			event: {
				eventTitle: {
					color: '#f4f3ee',
				},
			},
		},
		fonts: {
			h1: {
				activeFontID: '66f2b1919870deb1cc6eceb4',
				fontFamily: 'quiche-sans, sans-serif',
				fontSize: '42px',
				fontWeight: 700,
				lineHeight: 1.1,
				letterSpacing: '5px',
				fontStyle: 'normal',
				activeVariant: 4,
			},
			h2: {
				activeFontID: '66f2b1919870deb1cc6eceb4',
				fontFamily: 'quiche-sans, sans-serif',
				fontSize: '30px',
				fontWeight: 700,
				lineHeight: 1,
				letterSpacing: '0px',
				fontStyle: 'normal',
				activeVariant: 4,
			},
			h3: {
				activeFontID: '66f2b1919870deb1cc6eceb4',
				fontFamily: 'quiche-sans, sans-serif',
				fontSize: '24px',
				fontWeight: 700,
				lineHeight: 1,
				letterSpacing: '0px',
				fontStyle: 'normal',
				activeVariant: 4,
			},
			h4: {
				activeFontID: '66f2b1919870deb1cc6eceb4',
				fontFamily: 'quiche-sans, sans-serif',
				fontSize: '20px',
				fontWeight: 700,
				lineHeight: 1,
				letterSpacing: '0px',
				fontStyle: 'normal',
				activeVariant: 4,
			},
			h5: {
				activeFontID: '66f2b1919870deb1cc6eceb4',
				fontFamily: 'quiche-sans, sans-serif',
				fontSize: '18px',
				fontWeight: 700,
				lineHeight: 1,
				letterSpacing: '0px',
				fontStyle: 'normal',
				activeVariant: 4,
			},
			h6: {
				activeFontID: '66f2b1919870deb1cc6eceb4',
				fontFamily: 'quiche-sans, sans-serif',
				fontSize: '16px',
				fontWeight: 700,
				lineHeight: 1,
				letterSpacing: '0px',
				fontStyle: 'normal',
				activeVariant: 4,
			},
			p: {
				activeFontID: '66f2b1919870deb1cc6ece8e',
				fontFamily: 'Optima, sans-serif',
				fontSize: '18px',
				fontWeight: 400,
				lineHeight: 1,
				letterSpacing: '0px',
				activeVariant: 0,
				fontStyle: 'normal',
			},
			span: {
				activeFontID: '66f2b1919870deb1cc6ece8e',
				fontFamily: 'Optima, sans-serif',
				fontSize: '18px',
				fontWeight: 400,
				lineHeight: 1,
				letterSpacing: '0px',
				activeVariant: 0,
				fontStyle: 'normal',
			},
			buttons: {
				primary: {
					activeFontID: '66f2b1919870deb1cc6ece8e',
					fontFamily: 'Optima, sans-serif',
					fontSize: '14px',
					fontWeight: 400,
					lineHeight: 1,
					letterSpacing: '0px',
					activeVariant: 0,
					fontStyle: 'normal',
				},
				secondary: {
					activeFontID: '66f2b1919870deb1cc6ece8e',
					fontFamily: 'Optima, sans-serif',
					fontSize: '14px',
					fontWeight: 400,
					lineHeight: 1,
					letterSpacing: '0px',
					activeVariant: 0,
					fontStyle: 'normal',
				},
				tertiary: {
					activeFontID: '66f2b1919870deb1cc6ece8e',
					fontFamily: 'Optima, sans-serif',
					fontSize: '14px',
					fontWeight: 400,
					lineHeight: 1,
					letterSpacing: '0px',
					activeVariant: 0,
					fontStyle: 'normal',
				},
			},
			form: {
				inputQuestion: {
					activeFontID: '66f2b1919870deb1cc6ece8e',
					fontFamily: 'Optima, sans-serif',
					fontSize: '16px',
					fontWeight: 400,
					lineHeight: 1,
					letterSpacing: '0px',
				},
				inputDescription: {
					activeFontID: '66f2b1919870deb1cc6ece8e',
					fontFamily: 'Optima, sans-serif',
					fontSize: '16px',
					fontWeight: 400,
					lineHeight: 1,
					letterSpacing: '0px',
				},
				submitButton: {
					activeFontID: '66f2b1919870deb1cc6ece8e',
					fontFamily: 'Optima, sans-serif',
					fontSize: '16px',
					fontWeight: 400,
					lineHeight: 1,
					letterSpacing: '0px',
				},
				inputAnswer: {
					activeFontID: '66f2b1919870deb1cc6ece8e',
					fontFamily: 'Optima, sans-serif',
					fontSize: '16px',
					fontWeight: 400,
					lineHeight: 1,
					letterSpacing: '0px',
				},
				formHeading: {
					activeFontID: '66f2b1919870deb1cc6ece8e',
					fontFamily: 'Optima, sans-serif',
					fontSize: '16px',
					fontWeight: 400,
					lineHeight: 1,
					letterSpacing: '0px',
				},
				formDescription: {
					activeFontID: '66f2b1919870deb1cc6ece8e',
					fontFamily: 'Optima, sans-serif',
					fontSize: '16px',
					fontWeight: 400,
					lineHeight: 1,
					letterSpacing: '0px',
				},
			},
			event: {
				eventTitle: {
					activeFontID: '66f2b1919870deb1cc6ece8e',
					fontFamily: 'Optima, sans-serif',
					fontSize: '18px',
					fontWeight: 400,
					lineHeight: 1,
					letterSpacing: '0px',
					activeVariant: 0,
					fontStyle: 'normal',
				},
			},
		},
		mobileFonts: {
			h1: {
				fontSize: '29px',
			},
			h2: {
				fontSize: '24px',
			},
			h3: {
				fontSize: '20px',
			},
			h4: {
				fontSize: '18px',
			},
			h5: {
				fontSize: '16px',
			},
			h6: {
				fontSize: '14px',
			},
			p: {
				fontSize: '16px',
			},
			span: {
				fontSize: '16px',
			},
			event: {
				eventTitle: {
					fontSize: '14px',
				},
			},
		},
		buttons: {
			buttonType: 'primary',
			primary: {
				buttonShape: 'rounded',
				normal: {
					borderRadius: '20px',
					borderWidth: '1px',
					borderStyle: 'solid',
					paddingTop: '12px',
					paddingBottom: '12px',
					paddingRight: '18px',
					paddingLeft: '18px',
				},
				hover: {
					background: '#123047',
					borderColor: '#123047',
				},
			},
			secondary: {
				buttonShape: 'rounded',
				normal: {
					borderRadius: '16px',
					borderWidth: '2px',
					borderStyle: 'solid',
					paddingTop: '12px',
					paddingBottom: '12px',
					paddingRight: '16px',
					paddingLeft: '16px',
				},
				hover: {
					background: '#F5F8FA',
					borderColor: '#123047',
				},
			},
			tertiary: {
				buttonShape: 'rounded',
				normal: {
					borderRadius: '0px',
					borderWidth: '0px',
					borderStyle: 'none',
					paddingTop: '12px',
					paddingBottom: '12px',
					paddingRight: '16px',
					paddingLeft: '16px',
				},
				hover: {
					color: '#123047',
					border: 'none',
				},
			},
		},
		layout: {
			siteMaxWidth: '1280px',
			blockBackground: '#E8EFF5',
			defaultMargin: '32px',
		},
	},
	{
		id: 'theme5',
		name: 'Elegant Dark VE Theme',
		source: 've',
		category: 'Playfull',
		isDesktopMobileFontLinked: true,
		colors: {
			background: '#1E1E2F',
			background2: '#1E1E2F',
			text: {
				h1: { color: '#E8E8F5' },
				h2: { color: '#CCCCE3' },
				h3: { color: '#B4B4D6' },
				h4: { color: '#A0A0C3' },
				h5: { color: '#8C8CB8' },
				h6: { color: '#7878A8' },
				p: { color: '#A0A0C3' },
				span: { color: '#A0A0C3' },
			},
			shape: {
				color: '#2D2D44',
			},

			buttons: {
				primary: {
					normal: {
						background: '#2D2D44',
						color: '#FFFFFF',
						borderColor: '#5A5A89',
					},
					hover: {
						background: '#393956',
						color: '#FFFFFF',
						borderColor: '#7373A1',
					},
				},
				secondary: {
					normal: {
						background: '#45456A',
						color: '#FFFFFF',
						borderColor: '#6B6B94',
					},
					hover: {
						background: '#52527E',
						color: '#FFFFFF',
						borderColor: '#8282A7',
					},
				},
				tertiary: {
					normal: {
						background: 'transparent',
						color: '#A0A0C3',
						border: 'none',
					},
					hover: {
						color: '#E8E8F5',
						border: 'none',
					},
				},
			},
			form: {
				inputQuestion: {
					color: '#FFFFFF',
					borderColor: '#5A5A89',
				},
				inputDescription: {
					color: '#FFFFFF',
					borderColor: '#5A5A89',
				},
				submitButton: {
					background: '#2D2D44',
					color: '#FFFFFF',
					borderColor: '#5A5A89',
				},
				inputAnswer: {
					color: '#FFFFFF',
					borderColor: '#5A5A89',
				},
				formHeading: {
					color: '#FFFFFF',
					borderColor: '#5A5A89',
				},
				formDescription: {
					color: '#FFFFFF',
					borderColor: '#5A5A89',
				},
			},
			event: {
				evnetTitle: {
					color: '#FFFFFF',
				},
			},
		},
		fonts: {
			h1: {
				activeFontID: '66f2b1919870deb1cc6ece81',
				fontFamily: 'Courier, monospace',
				fontSize: '42px',
				fontWeight: 700,
				lineHeight: 1,
				letterSpacing: '0px',
				fontStyle: 'normal',
				activeVariant: 2,
			},
			h2: {
				activeFontID: '66f2b1919870deb1cc6ece81',
				fontFamily: 'Courier, monospace',
				fontSize: '30px',
				fontWeight: 700,
				lineHeight: 1,
				letterSpacing: '0px',
				fontStyle: 'normal',
				activeVariant: 2,
			},
			h3: {
				activeFontID: '66f2b1919870deb1cc6ece81',
				fontFamily: 'Courier, monospace',
				fontSize: '24px',
				fontWeight: 700,
				lineHeight: 1,
				letterSpacing: '0px',
				fontStyle: 'normal',
				activeVariant: 2,
			},
			h4: {
				activeFontID: '66f2b1919870deb1cc6ece81',
				fontFamily: 'Courier, monospace',
				fontSize: '20px',
				fontWeight: 700,
				lineHeight: 1,
				fontStyle: 'normal',
				activeVariant: 2,
			},
			h5: {
				activeFontID: '66f2b1919870deb1cc6ece81',
				fontFamily: 'Courier, monospace',
				fontSize: '18px',
				fontWeight: 700,
				lineHeight: 1,
				fontStyle: 'normal',
				activeVariant: 2,
			},
			h6: {
				activeFontID: '66f2b1919870deb1cc6ece81',
				fontFamily: 'Courier, monospace',
				fontSize: '16px',
				fontWeight: 700,
				lineHeight: 1,
				fontStyle: 'normal',
				activeVariant: 2,
			},
			p: {
				activeFontID: '66f2b1919870deb1cc6ece81',
				fontFamily: 'Courier, monospace',
				fontSize: '16px',
				fontWeight: 400,
				lineHeight: 1,
				letterSpacing: '0px',
				fontStyle: 'normal',
				activeVariant: 0,
			},
			span: {
				activeFontID: '66f2b1919870deb1cc6ece81',
				fontFamily: 'Courier, monospace',
				fontSize: '16px',
				fontWeight: 400,
				lineHeight: 1,
				letterSpacing: '0px',
				fontStyle: 'normal',
				activeVariant: 0,
			},
			buttons: {
				primary: {
					fontFamily: 'Inter',
					fontSize: '14px',
					fontStyle: 'normal',
					fontWeight: 500,
					lineHeight: '20px',
				},
				secondary: {
					fontFamily: 'Inter',
					fontSize: '14px',
					fontStyle: 'normal',
					fontWeight: 500,
					lineHeight: '20px',
				},
				tertiary: {
					fontFamily: 'Inter',
					fontSize: '14px',
					fontStyle: 'normal',
					fontWeight: 500,
					lineHeight: '20px',
				},
			},
			form: {
				inputQuestion: {
					activeFontID: '66f2b1919870deb1cc6ece81',
					fontFamily: 'Courier, monospace',
					fontSize: '16px',
					fontWeight: 400,
					lineHeight: 1,
					letterSpacing: '0px',
				},
				inputDescription: {
					activeFontID: '66f2b1919870deb1cc6ece81',
					fontFamily: 'Courier, monospace',
					fontSize: '16px',
					fontWeight: 400,
					lineHeight: 1,
					letterSpacing: '0px',
				},
				submitButton: {
					activeFontID: '66f2b1919870deb1cc6ece81',
					fontFamily: 'Courier, monospace',
					fontSize: '16px',
					fontWeight: 400,
					lineHeight: 1,
					letterSpacing: '0px',
				},
				inputAnswer: {
					activeFontID: '66f2b1919870deb1cc6ece81',
					fontFamily: 'Courier, monospace',
					fontSize: '16px',
					fontWeight: 400,
					lineHeight: 1,
					letterSpacing: '0px',
				},
				formHeading: {
					activeFontID: '66f2b1919870deb1cc6ece81',
					fontFamily: 'Courier, monospace',
					fontSize: '16px',
					fontWeight: 400,
					lineHeight: 1,
					letterSpacing: '0px',
				},
				formDescription: {
					activeFontID: '66f2b1919870deb1cc6ece81',
					fontFamily: 'Courier, monospace',
					fontSize: '16px',
					fontWeight: 400,
					lineHeight: 1,
					letterSpacing: '0px',
				},
			},
			event: {
				eventTitle: {
					activeFontID: '66f2b1919870deb1cc6ece81',
					fontFamily: 'Courier, monospace',
					fontSize: '16px',
					fontWeight: 400,
					lineHeight: 1,
					letterSpacing: '0px',
				},
			},
		},
		mobileFonts: {
			h1: {
				fontSize: '28px',
			},
			h2: {
				fontSize: '24px',
			},
			h3: {
				fontSize: '20px',
			},
			h4: {
				fontSize: '18px',
			},
			h5: {
				fontSize: '16px',
			},
			h6: {
				fontSize: '14px',
			},
			p: {
				fontSize: '14px',
			},
			span: {
				fontSize: '14px',
			},
			event: {
				eventTitle: {
					fontSize: '14px',
				},
			},
		},
		buttons: {
			buttonType: 'primary',
			primary: {
				buttonShape: 'rounded',
				normal: {
					borderRadius: '24px',
					borderWidth: '2px',
					borderStyle: 'solid',
					paddingTop: '14px',
					paddingBottom: '14px',
					paddingRight: '20px',
					paddingLeft: '20px',
				},
				hover: {
					background: '#393956',
					borderColor: '#7373A1',
				},
			},
			secondary: {
				buttonShape: 'rounded',
				normal: {
					borderRadius: '16px',
					borderWidth: '2px',
					borderStyle: 'solid',
					paddingTop: '14px',
					paddingBottom: '14px',
					paddingRight: '20px',
					paddingLeft: '20px',
				},
				hover: {
					background: '#52527E',
					borderColor: '#8282A7',
				},
			},
			tertiary: {
				buttonShape: 'rounded',
				normal: {
					borderRadius: '0px',
					borderWidth: '0px',
					borderStyle: 'none',
					paddingTop: '12px',
					paddingBottom: '12px',
					paddingRight: '16px',
					paddingLeft: '16px',
				},
				hover: {
					color: '#E8E8F5',
					border: 'none',
				},
			},
		},
		layout: {},
	},
];

// for colors list
export const ColorsListJson = [
	{
		id: 'colorTheme1',
		name: 'Bright 1',
		background: '#F7EDE2',
		background2: '#F7EDE2',
		text: {
			h1: { color: '#000000' },
			h2: { color: '#111111' },
			h3: { color: '#333333' },
			h4: { color: '#555555' },
			h5: { color: '#555555' },
			h6: { color: '#555555' },
			p: { color: '#555555' },
			span: { color: '#555555' },
		},
		shape: {
			color: '#F2F2F3',
		},
		buttons: {
			primary: {
				normal: {
					background: '#F2F2F3',
					color: '#0C0C0D',
					borderColor: '#0C0C0D',
				},
				hover: {},
			},
			secondary: {
				normal: {
					background: '#0C0C0D',
					color: '#F2F2F3',
					borderColor: '#F2F2F3',
				},
				hover: {},
			},
			tertiary: {
				normal: {
					background: 'transparent',
					color: '#F2F2F3',
					border: 'none',
				},
				hover: {},
			},
		},
		form: {
			inputQuestion: {
				color: '#0C0C0D',
				borderColor: '#0C0C0D',
			},
			inputDescription: {
				color: '#0C0C0D',
				borderColor: '#0C0C0D',
			},
			submitButton: {
				background: '#F2F2F3',
				color: '#0C0C0D',
				borderColor: '#0C0C0D',
			},
			inputAnswer: {
				color: '#0C0C0D',
				borderColor: '#0C0C0D',
			},
			formHeading: {
				color: '#0C0C0D',
				borderColor: '#0C0C0D',
			},
			formDescription: {
				color: '#0C0C0D',
				borderColor: '#0C0C0D',
			},
		},
		event: {
			eventTitle: {
				color: '#0C0C0D',
			},
		},
	},
	{
		id: 'colorTheme2',
		name: 'Bright & Sunny',
		background: '#FFF8E1',
		background2: '#FFF8E1',
		text: {
			h1: { color: '#FF9800' },
			h2: { color: '#FB8C00' },
			h3: { color: '#F57C00' },
			h4: { color: '#5D4037' },
			h5: { color: '#5D4037' },
			h6: { color: '#5D4037' },
			p: { color: '#5D4037' },
			span: { color: '#5D4037' },
		},
		shape: {
			color: '#FFCC80',
		},
		buttons: {
			primary: {
				normal: {
					background: '#FFCC80',
					color: '#3E2723',
					borderColor: '#3E2723',
				},
				hover: {
					background: '#FFB74D',
					color: '#3E2723',
					borderColor: '#3E2723',
				},
			},
			secondary: {
				normal: {
					background: '#3E2723',
					color: '#FFF8E1',
					borderColor: '#FFF8E1',
				},
				hover: {
					background: '#5D4037',
					color: '#FFF8E1',
					borderColor: '#FFF8E1',
				},
			},
			tertiary: {
				normal: {
					background: 'transparent',
					color: '#FF9800',
					border: 'none',
				},
				hover: {
					background: '#FFF3E0',
					color: '#FB8C00',
					border: 'none',
				},
			},
		},
		form: {
			inputQuestion: {
				color: '#3E2723',
				borderColor: '#3E2723',
			},
			inputDescription: {
				color: '#3E2723',
				borderColor: '#3E2723',
			},
			submitButton: {
				background: '#FFCC80',
				color: '#3E2723',
				borderColor: '#3E2723',
			},
			inputAnswer: {
				color: '#3E2723',
				borderColor: '#3E2723',
			},
			formHeading: {
				color: '#3E2723',
				borderColor: '#3E2723',
			},
			formDescription: {
				color: '#3E2723',
				borderColor: '#3E2723',
			},
		},
		event: {
			eventTitle: { color: '#5D4037' },
		},
	},
	{
		id: 'colorTheme3',
		name: 'Calm & Minimal',
		background: '#F5F5F5',
		background2: '#F5F5F5',
		text: {
			h1: { color: '#212121' },
			h2: { color: '#424242' },
			h3: { color: '#616161' },
			h4: { color: '#757575' },
			h5: { color: '#757575' },
			h6: { color: '#757575' },
			p: { color: '#757575' },
			span: { color: '#757575' },
		},
		shape: {
			color: '#E0E0E0',
		},
		buttons: {
			primary: {
				normal: {
					background: '#E0E0E0',
					color: '#212121',
					borderColor: '#BDBDBD',
				},
				hover: {
					background: '#BDBDBD',
					color: '#212121',
					borderColor: '#757575',
				},
			},
			secondary: {
				normal: {
					background: '#212121',
					color: '#FFFFFF',
					borderColor: '#E0E0E0',
				},
				hover: {
					background: '#424242',
					color: '#FFFFFF',
					borderColor: '#BDBDBD',
				},
			},
			tertiary: {
				normal: {
					background: 'transparent',
					color: '#757575',
					border: 'none',
				},
				hover: {
					background: '#F5F5F5',
					color: '#616161',
					border: 'none',
				},
			},
		},
		form: {
			inputQuestion: {
				color: '#212121',
				borderColor: '#BDBDBD',
			},
			inputDescription: {
				color: '#212121',
				borderColor: '#BDBDBD',
			},
			submitButton: {
				background: '#E0E0E0',
				color: '#212121',
				borderColor: '#BDBDBD',
			},
			inputAnswer: {
				color: '#212121',
				borderColor: '#BDBDBD',
			},
			formHeading: {
				color: '#212121',
				borderColor: '#BDBDBD',
			},
			formDescription: {
				color: '#212121',
				borderColor: '#BDBDBD',
			},
		},
		event: {
			eventTitle: { color: '#757575' },
		},
	},
	{
		id: 'colorTheme4',
		name: 'Cool & Modern',
		background: '#E3F2FD',
		background2: '#E3F2FD',
		text: {
			h1: { color: '#0288D1' },
			h2: { color: '#0277BD' },
			h3: { color: '#01579B' },
			h4: { color: '#01579B' },
			h5: { color: '#01579B' },
			h6: { color: '#01579B' },
			p: { color: '#01579B' },
			span: { color: '#01579B' },
		},
		shape: {
			color: '#81D4FA',
		},
		buttons: {
			primary: {
				normal: {
					background: '#81D4FA',
					color: '#01579B',
					borderColor: '#0288D1',
				},
				hover: {
					background: '#4FC3F7',
					color: '#01579B',
					borderColor: '#0277BD',
				},
			},
			secondary: {
				normal: {
					background: '#01579B',
					color: '#E3F2FD',
					borderColor: '#0288D1',
				},
				hover: {
					background: '#0277BD',
					color: '#E3F2FD',
					borderColor: '#01579B',
				},
			},
			tertiary: {
				normal: {
					background: 'transparent',
					color: '#0288D1',
					border: 'none',
				},
				hover: {
					background: '#E1F5FE',
					color: '#0277BD',
					border: 'none',
				},
			},
		},
		form: {
			inputQuestion: {
				color: '#01579B',
				borderColor: '#0288D1',
			},
			inputDescription: {
				color: '#01579B',
				borderColor: '#0288D1',
			},
			submitButton: {
				background: '#81D4FA',
				color: '#01579B',
				borderColor: '#0288D1',
			},
			inputAnswer: {
				color: '#01579B',
				borderColor: '#0288D1',
			},
			formHeading: {
				color: '#01579B',
				borderColor: '#0288D1',
			},
			formDescription: {
				color: '#01579B',
				borderColor: '#0288D1',
			},
		},
		event: {
			eventTitle: { color: '#01579B' },
		},
	},
];

// for fonts list
export const FontsListJson = [
	{
		h1: {
			activeFontID: '66f2b1919870deb1cc6eced1',
			fontFamily: 'Aviano Didone',
			fontSize: '30px',
			fontWeight: 900,
			lineHeight: 1,
			letterSpacing: '0px',
		},
		h2: {
			activeFontID: '66f2b1919870deb1cc6ece81',
			fontFamily: 'Courier, monospace',
			fontSize: '32px',
			fontWeight: 700,
			lineHeight: 1,
			letterSpacing: '0px',
		},
		h3: {
			activeFontID: '66f2b1919870deb1cc6ece81',
			fontFamily: 'Courier, monospace',
			fontSize: '28px',
			fontWeight: 600,
			lineHeight: 1,
			letterSpacing: '0px',
		},
		h4: {
			activeFontID: '66f2b1919870deb1cc6ece81',
			fontFamily: 'Courier, monospace',
			fontSize: '24px',
			fontWeight: 500,
			lineHeight: 1,
			letterSpacing: '0px',
		},
		h5: {
			activeFontID: '66f2b1919870deb1cc6ece81',
			fontFamily: 'Courier, monospace',
			fontSize: '20px',
			fontWeight: 400,
			lineHeight: 1,
			letterSpacing: '0px',
		},
		h6: {
			activeFontID: '66f2b1919870deb1cc6ece81',
			fontFamily: 'Courier, monospace',
			fontSize: '18px',
			fontWeight: 400,
			lineHeight: 1,
			letterSpacing: '0px',
		},
		p: {
			activeFontID: '66f2b1919870deb1cc6ece81',
			fontFamily: 'Courier, monospace',
			fontSize: '16px',
			fontWeight: 400,
			lineHeight: 1,
			letterSpacing: '0px',
		},
		span: {
			activeFontID: '66f2b1919870deb1cc6ece81',
			fontFamily: 'Courier, monospace',
			fontSize: '16px',
			fontWeight: 400,
			lineHeight: 1,
			letterSpacing: '0px',
		},
		buttons: {
			primary: {
				fontFamily: 'Inter',
				fontSize: '14px',
				fontStyle: 'normal',
				fontWeight: 500,
				lineHeight: '20px',
			},
			secondary: {
				fontFamily: 'Inter',
				fontSize: '14px',
				fontStyle: 'normal',
				fontWeight: 500,
				lineHeight: '20px',
			},
			tertiary: {
				fontFamily: 'Inter',
				fontSize: '14px',
				fontStyle: 'normal',
				fontWeight: 500,
				lineHeight: '20px',
			},
		},
		form: {
			inputQuestion: {
				activeFontID: '66f2b1919870deb1cc6ece81',
				fontFamily: 'Courier, monospace',
				fontSize: '16px',
				fontWeight: 400,
				lineHeight: 1,
				letterSpacing: '0px',
			},
			inputDescription: {
				activeFontID: '66f2b1919870deb1cc6ece81',
				fontFamily: 'Courier, monospace',
				fontSize: '16px',
				fontWeight: 400,
				lineHeight: 1,
				letterSpacing: '0px',
			},
			submitButton: {
				activeFontID: '66f2b1919870deb1cc6ece81',
				fontFamily: 'Courier, monospace',
				fontSize: '16px',
				fontWeight: 400,
				lineHeight: 1,
				letterSpacing: '0px',
			},
			inputAnswer: {
				activeFontID: '66f2b1919870deb1cc6ece81',
				fontFamily: 'Courier, monospace',
				fontSize: '16px',
				fontWeight: 400,
				lineHeight: 1,
				letterSpacing: '0px',
			},
			formHeading: {
				activeFontID: '66f2b1919870deb1cc6ece81',
				fontFamily: 'Courier, monospace',
				fontSize: '16px',
				fontWeight: 400,
				lineHeight: 1,
				letterSpacing: '0px',
			},
			formDescription: {
				activeFontID: '66f2b1919870deb1cc6ece81',
				fontFamily: 'Courier, monospace',
				fontSize: '16px',
				fontWeight: 400,
				lineHeight: 1,
				letterSpacing: '0px',
			},
		},
		event: {
			eventTitle: {
				activeFontID: '66f2b1919870deb1cc6ece81',
				fontFamily: 'Courier, monospace',
				fontSize: '16px',
				fontWeight: 400,
				lineHeight: 1,
				letterSpacing: '0px',
			},
		},
	},

	{
		h1: {
			activeFontID: '66f2b1919870deb1cc6ecee5',
			fontFamily: 'itc-benguiat, serif',
			fontSize: '36px',
			fontWeight: 700,
			lineHeight: 1,
			letterSpacing: '0px',
		},
		h2: {
			activeFontID: '66f2b1919870deb1cc6ece89',
			fontFamily: 'Futura, sans-serif',
			fontSize: '30px',
			fontWeight: 600,
			lineHeight: 1,
			letterSpacing: '0px',
		},
		h3: {
			activeFontID: '66f2b1919870deb1cc6ece89',
			fontFamily: 'Futura, sans-serif',
			fontSize: '24px',
			fontWeight: 500,
			lineHeight: 1,
			letterSpacing: '0px',
		},
		h4: {
			activeFontID: '66f2b1919870deb1cc6ece89',
			fontFamily: 'Futura, sans-serif',
			fontSize: '20px',
			fontWeight: 400,
			lineHeight: 1,
			letterSpacing: '0px',
		},
		h5: {
			activeFontID: '66f2b1919870deb1cc6ece89',
			fontFamily: 'Futura, sans-serif',
			fontSize: '18px',
			fontWeight: 400,
			lineHeight: 1,
			letterSpacing: '0px',
		},
		h6: {
			activeFontID: '66f2b1919870deb1cc6ece89',
			fontFamily: 'Futura, sans-serif',
			fontSize: '16px',
			fontWeight: 400,
			lineHeight: 1,
			letterSpacing: '0px',
		},
		p: {
			activeFontID: '66f2b1919870deb1cc6ece89',
			fontFamily: 'Futura, sans-serif',
			fontSize: '16px',
			fontWeight: 400,
			lineHeight: 1,
			letterSpacing: '0px',
		},
		span: {
			activeFontID: '66f2b1919870deb1cc6ece89',
			fontFamily: 'Futura, sans-serif',
			fontSize: '16px',
			fontWeight: 400,
			lineHeight: 1,
			letterSpacing: '0px',
		},
		buttons: {
			primary: {
				fontFamily: 'Source Sans Pro, sans-serif',
				fontSize: '14px',
				fontStyle: 'normal',
				fontWeight: 600,
				lineHeight: 1,
			},
			secondary: {
				fontFamily: 'Source Sans Pro, sans-serif',
				fontSize: '14px',
				fontStyle: 'normal',
				fontWeight: 600,
				lineHeight: 1,
			},
			tertiary: {
				fontFamily: 'Source Sans Pro, sans-serif',
				fontSize: '14px',
				fontStyle: 'normal',
				fontWeight: 600,
				lineHeight: 1,
			},
		},
		form: {
			inputQuestion: {
				activeFontID: '66f2b1919870deb1cc6ece89',
				fontFamily: 'Futura, sans-serif',
				fontSize: '16px',
				fontWeight: 400,
				lineHeight: 1,
				letterSpacing: '0px',
			},
			inputDescription: {
				activeFontID: '66f2b1919870deb1cc6ece89',
				fontFamily: 'Futura, sans-serif',
				fontSize: '16px',
				fontWeight: 400,
				lineHeight: 1,
				letterSpacing: '0px',
			},
			submitButton: {
				activeFontID: '66f2b1919870deb1cc6ece89',
				fontFamily: 'Futura, sans-serif',
				fontSize: '16px',
				fontWeight: 400,
				lineHeight: 1,
				letterSpacing: '0px',
			},
			inputAnswer: {
				activeFontID: '66f2b1919870deb1cc6ece89',
				fontFamily: 'Futura, sans-serif',
				fontSize: '16px',
				fontWeight: 400,
				lineHeight: 1,
				letterSpacing: '0px',
			},
			formHeading: {
				activeFontID: '66f2b1919870deb1cc6ece89',
				fontFamily: 'Futura, sans-serif',
				fontSize: '16px',
				fontWeight: 400,
				lineHeight: 1,
				letterSpacing: '0px',
			},
			formDescription: {
				activeFontID: '66f2b1919870deb1cc6ece89',
				fontFamily: 'Futura, sans-serif',
				fontSize: '16px',
				fontWeight: 400,
				lineHeight: 1,
				letterSpacing: '0px',
			},
		},
		event: {
			eventTitle: {
				activeFontID: '66f2b1919870deb1cc6ece89',
				fontFamily: 'Futura, sans-serif',
				fontSize: '16px',
				fontWeight: 400,
				lineHeight: 1,
				letterSpacing: '0px',
			},
		},
	},

	{
		h1: {
			activeFontID: '67d2f1e4033bd898bc2a501c',
			fontFamily: 'aston, sans serif',
			fontSize: '40px',
			fontWeight: 900,
			lineHeight: 1,
			letterSpacing: '0px',
		},
		h2: {
			activeFontID: '66f2b1919870deb1cc6ecebf',
			fontFamily: 'amsterdam-two, cursive',
			fontSize: '34px',
			fontWeight: 700,
			lineHeight: 1,
			letterSpacing: '0px',
		},
		h3: {
			activeFontID: '66f2b1919870deb1cc6ecebf',
			fontFamily: 'amsterdam-two, cursive',
			fontSize: '28px',
			fontWeight: 600,
			lineHeight: 1,
			letterSpacing: '0px',
		},
		h4: {
			activeFontID: '66f2b1919870deb1cc6ecebf',
			fontFamily: 'amsterdam-two, cursive',
			fontSize: '24px',
			fontWeight: 500,
			lineHeight: 1,
			letterSpacing: '0px',
		},
		h5: {
			activeFontID: '66f2b1919870deb1cc6ecebf',
			fontFamily: 'amsterdam-two, cursive',
			fontSize: '20px',
			fontWeight: 400,
			lineHeight: 1,
			letterSpacing: '0px',
		},
		h6: {
			activeFontID: '66f2b1919870deb1cc6ecebf',
			fontFamily: 'amsterdam-two, cursive',
			fontSize: '18px',
			fontWeight: 400,
			lineHeight: 1,
			letterSpacing: '0px',
		},
		p: {
			activeFontID: '66f2b1919870deb1cc6ecebf',
			fontFamily: 'amsterdam-two, cursive',
			fontSize: '18px',
			fontWeight: 400,
			lineHeight: 1,
			letterSpacing: '0px',
		},
		span: {
			activeFontID: '66f2b1919870deb1cc6ecebf',
			fontFamily: 'amsterdam-two, cursive',
			fontSize: '18px',
			fontWeight: 400,
			lineHeight: 1,
			letterSpacing: '0px',
		},
		buttons: {
			primary: {
				fontFamily: 'Roboto',
				fontSize: '16px',
				fontStyle: 'normal',
				fontWeight: 600,
				lineHeight: 1,
			},
			secondary: {
				fontFamily: 'Roboto',
				fontSize: '16px',
				fontStyle: 'normal',
				fontWeight: 600,
				lineHeight: 1,
			},
			tertiary: {
				fontFamily: 'Roboto',
				fontSize: '16px',
				fontStyle: 'normal',
				fontWeight: 600,
				lineHeight: 1,
			},
		},
		form: {
			inputQuestion: {
				activeFontID: '66f2b1919870deb1cc6ecebf',
				fontFamily: 'amsterdam-two, cursive',
				fontSize: '18px',
				fontWeight: 400,
				lineHeight: 1,
				letterSpacing: '0px',
			},
			inputDescription: {
				activeFontID: '66f2b1919870deb1cc6ecebf',
				fontFamily: 'amsterdam-two, cursive',
				fontSize: '18px',
				fontWeight: 400,
				lineHeight: 1,
				letterSpacing: '0px',
			},
			submitButton: {
				activeFontID: '66f2b1919870deb1cc6ecebf',
				fontFamily: 'amsterdam-two, cursive',
				fontSize: '18px',
				fontWeight: 400,
				lineHeight: 1,
				letterSpacing: '0px',
			},
			inputAnswer: {
				activeFontID: '66f2b1919870deb1cc6ecebf',
				fontFamily: 'amsterdam-two, cursive',
				fontSize: '18px',
				fontWeight: 400,
				lineHeight: 1,
				letterSpacing: '0px',
			},
			formHeading: {
				activeFontID: '66f2b1919870deb1cc6ecebf',
				fontFamily: 'amsterdam-two, cursive',
				fontSize: '18px',
				fontWeight: 400,
				lineHeight: 1,
				letterSpacing: '0px',
			},
			formDescription: {
				activeFontID: '66f2b1919870deb1cc6ecebf',
				fontFamily: 'amsterdam-two, cursive',
				fontSize: '18px',
				fontWeight: 400,
				lineHeight: 1,
				letterSpacing: '0px',
			},
		},
		event: {
			eventTitle: {
				activeFontID: '66f2b1919870deb1cc6ecebf',
				fontFamily: 'amsterdam-two, cursive',
				fontSize: '18px',
				fontWeight: 400,
				lineHeight: 1,
				letterSpacing: '0px',
			},
		},
	},

	{
		h1: {
			activeFontID: '67d2f1e4033bd898bc2a5036',
			fontFamily: 'wigan, sans serif',
			fontSize: '40px',
			fontWeight: 800,
			lineHeight: '48px',
			letterSpacing: '0.5px',
		},
		h2: {
			activeFontID: '67d2f1e4033bd898bc2a502b',
			fontFamily: 'oval, sans serif',
			fontSize: '32px',
			fontWeight: 700,
			lineHeight: 1,
			letterSpacing: '0.5px',
		},
		h3: {
			activeFontID: '67d2f1e4033bd898bc2a502b',
			fontFamily: 'oval, sans serif',
			fontSize: '24px',
			fontWeight: 600,
			lineHeight: 1,
			letterSpacing: '0px',
		},
		h4: {
			activeFontID: '67d2f1e4033bd898bc2a502b',
			fontFamily: 'oval, sans serif',
			fontSize: '20px',
			fontWeight: 400,
			lineHeight: 1,
			letterSpacing: '0px',
		},
		h5: {
			activeFontID: '67d2f1e4033bd898bc2a502b',
			fontFamily: 'oval, sans serif',
			fontSize: '18px',
			fontWeight: 400,
			lineHeight: 1,
			letterSpacing: '0px',
		},
		h6: {
			activeFontID: '67d2f1e4033bd898bc2a502b',
			fontFamily: 'oval, sans serif',
			fontSize: '16px',
			fontWeight: 400,
			lineHeight: 1,
			letterSpacing: '0px',
		},
		p: {
			activeFontID: '67d2f1e4033bd898bc2a502b',
			fontFamily: 'oval, sans serif',
			fontSize: '16px',
			fontWeight: 400,
			lineHeight: 1,
			letterSpacing: '0px',
		},
		span: {
			activeFontID: '67d2f1e4033bd898bc2a502b',
			fontFamily: 'oval, sans serif',
			fontSize: '16px',
			fontWeight: 400,
			lineHeight: 1,
			letterSpacing: '0px',
		},
		buttons: {
			primary: {
				fontFamily: 'Source Sans Pro, sans-serif',
				fontSize: '14px',
				fontStyle: 'normal',
				fontWeight: 600,
				lineHeight: 1,
			},
			secondary: {
				fontFamily: 'Source Sans Pro, sans-serif',
				fontSize: '14px',
				fontStyle: 'normal',
				fontWeight: 600,
				lineHeight: 1,
			},
			tertiary: {
				fontFamily: 'Source Sans Pro, sans-serif',
				fontSize: '14px',
				fontStyle: 'normal',
				fontWeight: 600,
				lineHeight: 1,
			},
		},
		form: {
			inputQuestion: {
				activeFontID: '67d2f1e4033bd898bc2a502b',
				fontFamily: 'oval, sans serif',
				fontSize: '16px',
				fontWeight: 400,
				lineHeight: 1,
				letterSpacing: '0px',
			},
			inputDescription: {
				activeFontID: '67d2f1e4033bd898bc2a502b',
				fontFamily: 'oval, sans serif',
				fontSize: '16px',
				fontWeight: 400,
				lineHeight: 1,
				letterSpacing: '0px',
			},
			submitButton: {
				activeFontID: '67d2f1e4033bd898bc2a502b',
				fontFamily: 'oval, sans serif',
				fontSize: '16px',
				fontWeight: 400,
				lineHeight: 1,
				letterSpacing: '0px',
			},
			inputAnswer: {
				activeFontID: '67d2f1e4033bd898bc2a502b',
				fontFamily: 'oval, sans serif',
				fontSize: '16px',
				fontWeight: 400,
				lineHeight: 1,
				letterSpacing: '0px',
			},
			formHeading: {
				activeFontID: '67d2f1e4033bd898bc2a502b',
				fontFamily: 'oval, sans serif',
				fontSize: '16px',
				fontWeight: 400,
				lineHeight: 1,
				letterSpacing: '0px',
			},
			formDescription: {
				activeFontID: '67d2f1e4033bd898bc2a502b',
				fontFamily: 'oval, sans serif',
				fontSize: '16px',
				fontWeight: 400,
				lineHeight: 1,
				letterSpacing: '0px',
			},
		},
		event: {
			eventTitle: {
				activeFontID: '67d2f1e4033bd898bc2a502b',
				fontFamily: 'oval, sans serif',
				fontSize: '16px',
				fontWeight: 400,
				lineHeight: 1,
				letterSpacing: '0px',
			},
		},
	},
];

export const responsiveFontSize = {
	1: 1,
	2: 2,
	3: 3,
	4: 4,
	5: 5,
	6: 6,
	7: 7,
	8: 8,
	9: 9,
	10: 10,
	11: 11,
	12: 12,
	13: 12,
	14: 12,
	15: 13,
	16: 14,
	17: 14,
	18: 16,
	19: 16,
	20: 18,
	21: 18,
	22: 19,
	23: 19,
	24: 20,
	25: 20,
	26: 21,
	27: 21,
	28: 22,
	29: 22,
	30: 23,
	31: 23,
	32: 24,
	33: 24,
	34: 25,
	35: 25,
	36: 26,
	37: 26,
	38: 27,
	39: 27,
	40: 28,
	41: 28,
	42: 29,
	43: 29,
	44: 30,
	45: 30,
	46: 31,
	47: 31,
	48: 32,
	49: 32,
	50: 33,
	51: 33,
	52: 34,
	53: 34,
	54: 35,
	55: 35,
	56: 36,
	57: 36,
	58: 37,
	59: 37,
	60: 38,
	61: 38,
	62: 39,
	63: 39,
	64: 40,
	65: 40,
	66: 41,
	67: 41,
	68: 42,
	69: 42,
	70: 43,
	71: 43,
	72: 44,
	73: 44,
	74: 45,
	75: 45,
	76: 46,
	77: 46,
	78: 47,
	79: 47,
	80: 48,
	81: 49,
	82: 50,
	83: 51,
	84: 52,
	85: 53,
	86: 54,
	87: 55,
	88: 56,
	89: 57,
	90: 58,
	91: 59,
	92: 60,
	93: 61,
	94: 62,
	95: 63,
	96: 64,
	97: 65,
	98: 66,
	99: 67,
	100: 68,
};
