export const Actions = {
	GET_ALL_SUBSCRIPTION_PLAN_SUCCESS: 'GET_ALL_SUBSCRIPTION_PLAN_SUCCESS',
	GET_ALL_COUPONS_SUCCESS: 'GET_ALL_COUPONS_SUCCESS',
	GET_ALL_CURRENT_PLAN_SUCCESS: 'GET_ALL_CURRENT_PLAN_SUCCESS',
	GET_SHARE_AND_EARN_SUCCESS: 'GET_SHARE_AND_EARN_SUCCESS',
	GET_REFERRAL_DETAILS_SUCCESS: 'GET_REFERRAL_DETAILS_SUCCESS',
	GET_ONBOARD_POSITION_SUCCESS: 'GET_ONBOARD_POSITION_SUCCESS',
	SEND_CUSTOM_MAIL_SUCCESS: 'SEND_CUSTOM_MAIL_SUCCESS',
	RESET_STATE: 'RESET_STATE',
};
