export const Actions = {
	GET_ALL_SUBSCRIPTION_PLAN_SUCCESS: 'GET_ALL_SUBSCRIPTION_PLAN_SUCCESS',
	GET_ALL_COUPONS_SUCCESS: 'GET_ALL_COUPONS_SUCCESS',
	GET_ALL_CURRENT_PLAN_SUCCESS: 'GET_ALL_CURRENT_PLAN_SUCCESS',
	GET_SHARE_AND_EARN_SUCCESS: 'GET_SHARE_AND_EARN_SUCCESS',
	RESET_STATE: 'RESET_STATE',
};
